apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: rhoai3-demo
      demo.rhoai.io/stage: "230"

resources:
  - project/base
  - postgresql/base
  - milvus/base
  - reranker/base
  - llamastack/base
  - workbench/base
