apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: rhoai3-demo
      demo.rhoai.io/stage: "230"

resources:
  - project/base
  - rhoai-dsc/base
  - postgresql/base
  - milvus/base
  - pipelines/base
  - reranker/base
  - llamastack/base
  - workbench/base
  - app/base
  - dashboard/base

transformers:
  - transformers/odhapplication-dashboard-labels.yaml
