apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-mcp
  namespace: private-ai
  labels:
    app.kubernetes.io/part-of: mcp-integration
  annotations:
    argocd.argoproj.io/sync-wave: "3"
