apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: rhoai3-demo
      demo.rhoai.io/stage: "230"

resources:
  - prerequisites/lws/base
  - prerequisites/rhcl/base
  - database/base
  - access/base
  - gateway/base
  - governance/base
  - local-models/base
  - tenant/base
  - external-models/base
  - policies/base
  - jobs/base
