# =============================================================================
# InferenceService: Devstral 2 24B (Coding Model)
# =============================================================================
# Deploys Devstral 2 - a code-optimized LLM for software development tasks.
# Uses 4x NVIDIA L4 GPUs with extended context window for code generation.
#
# Hardware: g6.12xlarge (4x NVIDIA L4, 96GB total VRAM)
# vLLM Args: --tensor-parallel-size 4 --dtype bfloat16 --max-model-len 32768
#
# Use Case: Code generation, code review, technical documentation
# =============================================================================
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: devstral-2-bf16
  namespace: private-ai
  labels:
    opendatahub.io/dashboard: "true"
    kueue.x-k8s.io/queue-name: default
    networking.kserve.io/visibility: exposed
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    openshift.io/display-name: "Devstral 2 24B BF16 (4-GPU, Coding)"
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-runtime
      # Use storage.key to reference the Data Connection secret
      storage:
        key: minio-connection
        path: devstral-2-24b/
      resources:
        requests:
          cpu: "8"
          memory: 64Gi
          nvidia.com/gpu: "4"
        limits:
          cpu: "16"
          memory: 128Gi
          nvidia.com/gpu: "4"
