# =============================================================================
# InferenceService: Granite 7B Lab (Coding Model)
# =============================================================================
# Deploys IBM Granite 7B Lab model using Red Hat validated OCI image.
# This is a code-optimized model for software development tasks.
#
# Hardware: g6.4xlarge (1x NVIDIA L4, 24GB VRAM)
# Use Case: Code generation, code review, technical documentation
#
# Note: Using Granite 7B as Red Hat validated alternative to Devstral
# =============================================================================
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-7b-lab
  namespace: private-ai
  labels:
    opendatahub.io/dashboard: "true"
    kueue.x-k8s.io/queue-name: default
    networking.kserve.io/visibility: exposed
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    # Hardware Profile integration
    opendatahub.io/hardware-profile-name: nvidia-l4-1gpu
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    # Display name for Dashboard
    openshift.io/display-name: "Granite 7B Lab (Coding)"
    # Deployment mode
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    # Note: nodeSelector and tolerations are managed by Kueue ResourceFlavors
    # via the Hardware Profile integration. Do not add them here.
    model:
      modelFormat:
        name: vLLM
      name: ""
      runtime: vllm-runtime
      # Red Hat validated Granite model via OCI registry (same as granite-test-2)
      storageUri: oci://registry.redhat.io/rhelai1/modelcar-granite-7b-redhat-lab:1.4.0
      resources:
        requests:
          cpu: "8"
          memory: 32Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "16"
          memory: 60Gi
          nvidia.com/gpu: "1"
