# =============================================================================
# InferenceService: Granite-3.1-8B-Agent (1-GPU FP8)
# =============================================================================
# Red Hat Validated Model (May 2025 Collection)
#
# Model: RedHatAI/granite-3.1-8b-instruct-FP8-dynamic
# Precision: FP8 Dynamic - 8B parameters, ~8GB VRAM
# Hardware: g6.4xlarge (1x NVIDIA L4, 24GB VRAM)
#
# Use Case: The Agentic Core - Tool-calling, Function-calling, and RAG.
# "Small but Mighty" - optimized for multi-step reasoning and API orchestration.
#
# Features:
#   - Native tool-calling support (built-in chat template in tokenizer_config.json)
#   - Auto tool choice via --tool-call-parser=granite for Agent Playground
#   - 16k context window for long RAG contexts
#
# Demo Role: "Queued Asset" - Key model for Step 06 (Agent Playground)
# =============================================================================
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-8b-agent
  namespace: private-ai
  labels:
    # Kubernetes recommended labels
    app.kubernetes.io/name: granite-8b-agent
    app.kubernetes.io/component: inference
    app.kubernetes.io/part-of: llm-serving
    app.kubernetes.io/managed-by: argocd
    # OpenShift AI Dashboard labels
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"  # AI Asset Endpoint for Playground
    # Kueue/KServe labels
    kueue.x-k8s.io/queue-name: default
    networking.kserve.io/visibility: exposed
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    opendatahub.io/hardware-profile-name: nvidia-l4-1gpu
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    openshift.io/display-name: "Granite-3.1-8B Agent (1-GPU FP8)"
    serving.kserve.io/deploymentMode: RawDeployment
    # AI Asset / Playground metadata
    opendatahub.io/model-type: generative
    opendatahub.io/genai-use-case: "agentic tool-calling"
    security.opendatahub.io/enable-auth: "false"
spec:
  predictor:
    # QUEUED ASSET: Starts at 0 replicas
    # Toggle via GPU Switchboard for Agentic demo
    minReplicas: 0
    maxReplicas: 1
    # Deployment Strategy: Recreate prevents Kueue deadlock
    # With RollingUpdate, new pods are SchedulingGated by Kueue while old pods
    # hold GPU quota, causing a deadlock. Recreate terminates old pods first.
    deploymentStrategy:
      type: Recreate
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    nodeSelector:
      node.kubernetes.io/instance-type: g6.4xlarge
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-runtime
      # S3 Storage - FP8 model (~8GB) could use OCI, but S3 for consistency
      storageUri: s3://models/granite-3.1-8b-instruct-fp8/
      storage:
        key: minio-connection
      args:
        # FP8 Dynamic (compressed-tensors format, auto-detected by vLLM)
        # 8B model = ~8GB, leaving 16GB for KV cache (16k+ context)
        - --served-model-name=granite-8b-agent
        # Note: --quantization removed - model uses compressed-tensors, auto-detected
        - --max-model-len=16384
        - --gpu-memory-utilization=0.9
        - --trust-remote-code
        # Agentic features - REQUIRED for tool-calling
        - --enable-auto-tool-choice
        - --tool-call-parser=granite
      env:
        # RHOAI 3.0 GA: V1 engine required
        - name: VLLM_USE_V1
          value: "1"
        - name: VLLM_NO_HW_METRICS
          value: "1"
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
      resources:
        requests:
          cpu: "8"
          memory: 32Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "16"
          memory: 60Gi
          nvidia.com/gpu: "1"

