# =============================================================================
# InferenceService: Mistral Small 24B Instruct (4-GPU Tensor Parallel)
# =============================================================================
# Deploys Mistral Small 24B using Red Hat validated OCI image with 4-GPU
# tensor parallelism for maximum throughput and lower latency.
#
# Hardware: g6.12xlarge (4x NVIDIA L4, 96GB total VRAM)
# Use Case: High-throughput production workloads
# =============================================================================
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mistral-small-24b-tp4
  namespace: private-ai
  labels:
    opendatahub.io/dashboard: "true"
    kueue.x-k8s.io/queue-name: default
    networking.kserve.io/visibility: exposed
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    # Hardware Profile integration
    opendatahub.io/hardware-profile-name: nvidia-l4-4gpu
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    # Display name for Dashboard
    openshift.io/display-name: "Mistral Small 24B TP4 (4-GPU)"
    # Deployment mode
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    # nodeSelector and tolerations are injected by Kueue via ResourceFlavor
    # HardwareProfile (nvidia-l4-4gpu) → LocalQueue → ClusterQueue → ResourceFlavor
    model:
      modelFormat:
        name: vLLM
      name: ""
      runtime: vllm-runtime
      # Red Hat validated Mistral model via OCI registry
      storageUri: oci://registry.redhat.io/rhelai1/mistral-small-24b-instruct-2501:1.5
      resources:
        requests:
          cpu: "8"
          memory: 64Gi
          nvidia.com/gpu: "4"
          ephemeral-storage: "60Gi"  # Model weights + cache
        limits:
          cpu: "16"
          memory: 128Gi
          nvidia.com/gpu: "4"
          ephemeral-storage: "100Gi"
