# =============================================================================
# InferenceService: Mistral 3 24B Instruct (Full Precision BF16)
# =============================================================================
# Deploys Mistral Small 3 using 4x NVIDIA L4 GPUs with tensor parallelism.
# This configuration prioritizes maximum quality over efficiency.
#
# Hardware: g6.12xlarge (4x NVIDIA L4, 96GB total VRAM)
# vLLM Args: --tensor-parallel-size 4 --dtype bfloat16
#
# Use Case: Production workloads requiring highest accuracy
# =============================================================================
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mistral-3-bf16
  namespace: private-ai
  labels:
    opendatahub.io/dashboard: "true"
    kueue.x-k8s.io/queue-name: default
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    openshift.io/display-name: "Mistral 3 24B BF16 (4-GPU)"
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/autoscalerClass: hpa
    serving.kserve.io/minScale: "1"
    serving.kserve.io/maxScale: "1"
spec:
  predictor:
    model:
      modelFormat:
        name: vllm
      runtime: vllm-runtime
      storageUri: "s3://models/mistral-3-24b-instruct/"
      args:
        - "--model"
        - "/mnt/models"
        - "--tensor-parallel-size"
        - "4"
        - "--dtype"
        - "bfloat16"
        - "--max-model-len"
        - "8192"
        - "--gpu-memory-utilization"
        - "0.9"
    resources:
      requests:
        cpu: "8"
        memory: "64Gi"
        nvidia.com/gpu: "4"
      limits:
        cpu: "16"
        memory: "128Gi"
        nvidia.com/gpu: "4"
    nodeSelector:
      nvidia.com/gpu.product: NVIDIA-L4
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule

