# =============================================================================
# InferenceService: Mistral 3 24B Instruct FP8 (Quantized)
# =============================================================================
# Deploys Mistral Small 3 FP8-quantized using 1x NVIDIA L4 GPU.
# Neural Magic optimized weights for Ada Lovelace FP8 acceleration.
# Configuration aligned with RHOAI 3.0 Dashboard-deployed models.
#
# Hardware: g6.4xlarge (1x NVIDIA L4, 24GB VRAM, ~15GB used)
# Key Benefits:
# - 50% memory reduction vs BF16
# - Native FP8 hardware acceleration on L4
# - Near-identical accuracy (Neural Magic kernels)
# - 4x cost reduction (1 GPU vs 4 GPUs)
#
# Use Case: Cost-efficient inference for most production workloads
# =============================================================================
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mistral-3-fp8
  namespace: private-ai
  labels:
    opendatahub.io/dashboard: "true"
    kueue.x-k8s.io/queue-name: default
    networking.kserve.io/visibility: exposed
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    # Hardware Profile integration
    opendatahub.io/hardware-profile-name: nvidia-l4-1gpu
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    # Display name for Dashboard
    openshift.io/display-name: "Mistral 3 24B FP8 (1-GPU, Optimized)"
    # Deployment mode
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    # GPU node scheduling
    nodeSelector:
      nvidia.com/gpu.product: NVIDIA-L4
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    model:
      modelFormat:
        name: vLLM
      name: ""
      runtime: vllm-runtime
      # S3 storage reference via Data Connection
      storage:
        key: minio-connection
        path: mistral-3-24b-instruct-fp8/
      resources:
        requests:
          cpu: "8"
          memory: 32Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "16"
          memory: 60Gi
          nvidia.com/gpu: "1"
