# =============================================================================
# InferenceService: Mistral Small 24B Instruct (1-GPU INT4 W4A16)
# =============================================================================
# RED HAT VALIDATED MODELCAR - Neural Magic INT4 Quantization
#
# Model: registry.redhat.io/rhelai1/modelcar-mistral-small-24b-instruct-2501-quantized-w4a16:1.5
# Quantization: INT4 weights, FP16 activations (W4A16)
#   - 4-bit weights: ~13.5GB (75% reduction from BF16)
#   - Leaves ~8.5GB for KV cache = 4k-8k context window
#   - 98.9% accuracy recovery vs full precision
#   - Red Hat validated for RHOAI 3.0
#
# Hardware: g6.4xlarge (1x NVIDIA L4, 24GB VRAM)
# Use Case: Cost-efficient 1-GPU inference with 75% cost savings vs 4-GPU BF16
# =============================================================================
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mistral-small-24b
  namespace: private-ai
  labels:
    opendatahub.io/dashboard: "true"
    kueue.x-k8s.io/queue-name: default
    networking.kserve.io/visibility: exposed
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    opendatahub.io/hardware-profile-name: nvidia-l4-1gpu
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    openshift.io/display-name: "Mistral Small 24B (1-GPU INT4)"
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    nodeSelector:
      node.kubernetes.io/instance-type: g6.4xlarge
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-runtime
      # Red Hat Validated ModelCar - OCI Image with INT4 weights
      storageUri: oci://registry.redhat.io/rhelai1/modelcar-mistral-small-24b-instruct-2501-quantized-w4a16:1.5
      args:
        # INT4 W4A16 Quantized - Neural Magic optimized for single L4 (24GB VRAM)
        # Model weights: ~13.5GB | KV Cache: ~8.5GB | Context: 4096 tokens
        - --served-model-name=mistral-small-24b
        - --max-model-len=4096
        - --gpu-memory-utilization=0.9
        - --trust-remote-code
      env:
        # RHOAI 3.0 GA: V1 engine required (assertion enforced by image)
        # Driver 570.195.03 provides CUDA 12.x compatibility
        - name: VLLM_USE_V1
          value: "1"
        - name: VLLM_NO_HW_METRICS
          value: "1"
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
      resources:
        requests:
          cpu: "8"
          memory: 32Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "16"
          memory: 60Gi
          nvidia.com/gpu: "1"
