# =============================================================================
# InferenceService: Mistral Small 24B Instruct (1-GPU AWQ 4-bit)
# =============================================================================
# RHOAI 3.0 OFFICIAL APPROACH: S3 Storage + KServe Storage Initializer
#
# AWQ (Activation-aware Weight Quantization) is the recommended quantization
# for fitting 24B models on a single NVIDIA L4 (24GB VRAM):
#   - 4-bit weights: ~13.5GB (vs 21.5GB FP8, 48GB BF16)
#   - Leaves ~8.5GB for KV cache = 8k context window
#   - Higher accuracy than GPTQ
#   - Native vLLM kernel support
#
# Hardware: g6.4xlarge (1x NVIDIA L4, 24GB VRAM)
# Use Case: Cost-efficient 1-GPU inference with 75% cost savings vs 4-GPU BF16
#
# Prerequisites:
#   1. Model weights uploaded to: s3://models/mistral-small-24b-awq/
#   2. storage-config secret with minio-connection key in private-ai namespace
# =============================================================================
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mistral-small-24b
  namespace: private-ai
  labels:
    opendatahub.io/dashboard: "true"
    kueue.x-k8s.io/queue-name: default
    networking.kserve.io/visibility: exposed
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    opendatahub.io/hardware-profile-name: nvidia-l4-1gpu
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    openshift.io/display-name: "Mistral Small 24B (1-GPU AWQ)"
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    nodeSelector:
      node.kubernetes.io/instance-type: g6.4xlarge
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-runtime
      # S3 Storage URI - KServe storage-initializer downloads weights at startup
      storageUri: s3://models/mistral-small-24b-awq/
      storage:
        key: minio-connection
      args:
        # AWQ 4-bit Quantized - optimized for single L4 (24GB VRAM)
        # Model weights: ~13.5GB | KV Cache: ~8.5GB | Context: 8192 tokens
        - --served-model-name=mistral-small-24b
        - --quantization=awq
        - --max-model-len=8192
        - --gpu-memory-utilization=0.9
        - --trust-remote-code
      env:
        # RHOAI 3.0 GA: V1 engine required (assertion enforced by image)
        # Driver 570.195.03 provides CUDA 12.x compatibility
        - name: VLLM_USE_V1
          value: "1"
        - name: VLLM_NO_HW_METRICS
          value: "1"
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
      resources:
        requests:
          cpu: "8"
          memory: 32Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "16"
          memory: 60Gi
          nvidia.com/gpu: "1"
