# ClusterPolicy configures NVIDIA GPU Operator components
# Ref: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/openshift/contents.html
#
# IMPORTANT: Driver version pinned to 570.195.03 for RHOAI 3.0 compatibility
# GPU Operator 25.10.1 defaults to driver 580.105.08 (CUDA 13.0) which is incompatible
# with RHOAI 3.0 vLLM images (built with CUDA 12.8)
# See: https://access.redhat.com/solutions/7134740
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  operator:
    defaultRuntime: crio
    use_ocp_driver_toolkit: true
  
  daemonsets:
    updateStrategy: RollingUpdate
    rollingUpdate:
      maxUnavailable: "1"
    # Allow GPU Operator DaemonSets to run on tainted GPU nodes
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
  
  # Driver version pinned for RHOAI 3.0 / vLLM CUDA 12.8 compatibility
  # Ref: https://access.redhat.com/solutions/7134740
  driver:
    enabled: true
    repository: nvcr.io/nvidia
    image: driver
    version: "570.195.03"
  
  dcgm:
    enabled: true
  
  dcgmExporter:
    enabled: true
    serviceMonitor:
      enabled: true
  
  devicePlugin:
    enabled: true
  
  gfd:
    enabled: true
  
  migManager:
    enabled: true
  
  nodeStatusExporter:
    enabled: true
  
  toolkit:
    enabled: true

