# Vendored from redhat-cop/gitops-catalog
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-nfd
  namespace: openshift-nfd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  targetNamespaces:
    - openshift-nfd

