# RoleBinding for ai-admin to have full Model Registry access
# Admins can archive/delete models, manage versions, etc.
#
# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.0/html-single/managing_model_registries/index#managing-model-registry-permissions_model-reg
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-admin-registry-admin
  namespace: rhoai-model-registries
  annotations:
    argocd.argoproj.io/sync-wave: "10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ai-admin
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: rhoai-admins
