apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-01-gpu
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/adnan-drina/rhoai3-demo.git
    targetRevision: main
    path: gitops/step-01-gpu/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    # Subscription fields managed by OLM
    - group: operators.coreos.com
      kind: Subscription
      jqPathExpressions:
        - .spec.installPlanApproval
        - .spec.startingCSV
    # ClusterPolicy fields managed by GPU Operator
    - group: nvidia.com
      kind: ClusterPolicy
      jqPathExpressions:
        - .spec
    # NFD instance fields managed by operator
    - group: nfd.openshift.io
      kind: NodeFeatureDiscovery
      jqPathExpressions:
        - .spec
