apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-05-llm-on-vllm
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: rhoai-demo
    demo-step: "05"
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/adnan-drina/rhoai3-demo.git
    targetRevision: main
    path: gitops/step-05-llm-on-vllm/base
  destination:
    server: https://kubernetes.default.svc
    namespace: private-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

