apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-04-model-registry
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: rhoai3-demo
    demo.rhoai.io/step: "04"
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/adnan-drina/rhoai3-demo.git
    targetRevision: main
    path: gitops/step-04-model-registry/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Ignore PVC status differences (WaitForFirstConsumer causes Pending state)
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /status
