apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-07-model-performance-metrics
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/adnan-drina/rhoai3-demo.git
    targetRevision: main
    path: gitops/step-07-model-performance-metrics/base
  destination:
    server: https://kubernetes.default.svc
    namespace: private-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    # ConfigMap for dashboards might have transient fields or console-managed annotations
    - group: ""
      kind: ConfigMap
      namespace: private-ai
      jsonPointers:
        - /metadata/annotations
        - /metadata/resourceVersion

