apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-03-private-ai
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/adnan-drina/rhoai3-demo.git
    targetRevision: main
    path: gitops/step-03-private-ai/base
  destination:
    server: https://kubernetes.default.svc
  # Ignore diff for Group resources - ArgoCD can't parse user.openshift.io/v1 Group
  ignoreDifferences:
    - group: user.openshift.io
      kind: Group
      jsonPointers:
        - /users
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
