apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-02-rhoai
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/adnan-drina/rhoai3-demo.git
    targetRevision: main
    path: gitops/step-02-rhoai/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: datasciencecluster.opendatahub.io
      kind: DataScienceCluster
      jqPathExpressions:
        - .spec.components
    - group: dscinitialization.opendatahub.io
      kind: DSCInitialization
      jqPathExpressions:
        - .spec
    - group: opendatahub.io
      kind: OdhDashboardConfig
      jqPathExpressions:
        - .spec
