# =============================================================================
# vLLM ServingRuntime for RHOAI 3.0
# =============================================================================
# High-performance LLM inference engine with support for:
# - FP8/FP16/BF16 quantization
# - Tensor parallelism (multi-GPU)
# - PagedAttention for efficient memory management
# - Continuous batching for high throughput
# - OpenAI-compatible API
#
# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.0/html-single/deploying_models/index
# =============================================================================
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: vllm-runtime
  namespace: private-ai
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    # Dashboard display annotations
    openshift.io/display-name: "vLLM Runtime for LLMs"
    opendatahub.io/template-name: "vllm-runtime"
    opendatahub.io/template-display-name: "vLLM ServingRuntime for KServe"
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    # Enable external route generation
    enable-route: "true"
spec:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
  multiModel: false
  supportedModelFormats:
    - name: vllm
      autoSelect: true
  containers:
    - name: kserve-container
      # RHOAI 3.0 vLLM image with FP8 and tensor parallelism support
      image: registry.redhat.io/rhoai/vllm-openai-rhel9:1.5
      command:
        - python
        - -m
        - vllm.entrypoints.openai.api_server
      args:
        - "--model"
        - "/mnt/models"
        - "--port"
        - "8080"
        - "--served-model-name"
        - "{{.Name}}"
        # Memory optimization
        - "--gpu-memory-utilization"
        - "0.9"
        # Enable chunked prefill for better latency
        - "--enable-chunked-prefill"
        - "true"
        # Trust remote code for custom models
        - "--trust-remote-code"
      env:
        - name: HF_HOME
          value: /tmp/hf_home
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
        # Disable CUDA graphs for better compatibility
        - name: VLLM_DISABLE_CUDA_GRAPHS
          value: "false"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /health
          port: http
        initialDelaySeconds: 180
        periodSeconds: 30
        timeoutSeconds: 10
        failureThreshold: 5
      readinessProbe:
        httpGet:
          path: /health
          port: http
        initialDelaySeconds: 120
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 5
      resources:
        requests:
          cpu: "4"
          memory: "16Gi"
        limits:
          cpu: "16"
          memory: "64Gi"
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
        - name: tmp
          mountPath: /tmp
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 32Gi
    - name: tmp
      emptyDir: {}
