# HardwareProfile - NVIDIA L4 4GPUs (Kueue-managed)
# AWS g6.12xlarge: 48 vCPU, 192 GB RAM, 4x NVIDIA L4 GPU
# Note: maxCount reduced to account for system overhead
apiVersion: infrastructure.opendatahub.io/v1
kind: HardwareProfile
metadata:
  name: nvidia-l4-4gpu
  namespace: private-ai
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    opendatahub.io/display-name: "NVIDIA L4 4GPUs"
    opendatahub.io/description: "AWS g6.12xlarge - 4x L4 GPU for distributed inference"
    opendatahub.io/disabled: "false"
  labels:
    app.kubernetes.io/part-of: hardwareprofile
    app.opendatahub.io/hardwareprofile: "true"
spec:
  # Queue-based scheduling for Kueue integration
  # Kueue's ClusterQueue/ResourceFlavor handles node selection
  scheduling:
    type: Queue
    kueue:
      localQueueName: default
  identifiers:
    - identifier: cpu
      displayName: CPU
      resourceType: CPU
      minCount: 1
      maxCount: 46  # g6.12xlarge has 48 vCPU, reserve for overhead
      defaultCount: 24
    - identifier: memory
      displayName: Memory
      resourceType: Memory
      minCount: 8Gi
      maxCount: 180Gi  # g6.12xlarge has 192GB, reserve for overhead
      defaultCount: 96Gi
    - identifier: nvidia.com/gpu
      displayName: NVIDIA L4 GPU
      resourceType: Accelerator
      minCount: 1
      maxCount: 4
      defaultCount: 4
