# HardwareProfile - NVIDIA L4 1GPU (Kueue-managed)
# AWS g6.4xlarge: 16 vCPU, 64 GB RAM, 1x NVIDIA L4 GPU
# Note: maxCount reduced to account for system overhead
apiVersion: infrastructure.opendatahub.io/v1
kind: HardwareProfile
metadata:
  name: nvidia-l4-1gpu
  namespace: private-ai
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    opendatahub.io/display-name: "NVIDIA L4 1GPU"
    opendatahub.io/description: "AWS g6.4xlarge - 1x L4 GPU for inference"
    opendatahub.io/disabled: "false"
  labels:
    app.kubernetes.io/part-of: hardwareprofile
    app.opendatahub.io/hardwareprofile: "true"
spec:
  # Queue-based scheduling for Kueue integration
  # Kueue's ClusterQueue/ResourceFlavor handles node selection
  scheduling:
    type: Queue
    kueue:
      localQueueName: default
  identifiers:
    - identifier: cpu
      displayName: CPU
      resourceType: CPU
      minCount: 1
      maxCount: 14  # g6.4xlarge has 16 vCPU, reserve for overhead
      defaultCount: 8
    - identifier: memory
      displayName: Memory
      resourceType: Memory
      minCount: 4Gi
      maxCount: 60Gi  # g6.4xlarge has 64GB, reserve for overhead
      defaultCount: 32Gi
    - identifier: nvidia.com/gpu
      displayName: NVIDIA L4 GPU
      resourceType: Accelerator
      minCount: 1
      maxCount: 1
      defaultCount: 1
