# HardwareProfile - NVIDIA L4 1GPU (AWS g6.4xlarge)
# Node specs: 16 vCPU, 64 GB RAM, 1x NVIDIA L4 GPU
apiVersion: infrastructure.opendatahub.io/v1
kind: HardwareProfile
metadata:
  name: nvidia-l4-1gpu
  namespace: private-ai
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    opendatahub.io/display-name: "NVIDIA L4 1GPU"
    opendatahub.io/description: "AWS g6.4xlarge - Single NVIDIA L4 GPU for inference workloads"
    opendatahub.io/disabled: "false"
  labels:
    app.kubernetes.io/part-of: hardwareprofile
    app.opendatahub.io/hardwareprofile: "true"
spec:
  scheduling:
    type: Node
    node:
      nodeSelector:
        node-role.kubernetes.io/gpu: ""
        node.kubernetes.io/instance-type: g6.4xlarge
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
  identifiers:
    - identifier: cpu
      displayName: CPU
      resourceType: CPU
      minCount: 1
      maxCount: "16"
      defaultCount: "8"
    - identifier: memory
      displayName: Memory
      resourceType: Memory
      minCount: 4Gi
      maxCount: 64Gi
      defaultCount: 32Gi
    - identifier: nvidia.com/gpu
      displayName: NVIDIA L4 GPU
      resourceType: Accelerator
      minCount: 1
      maxCount: 1
      defaultCount: 1

