# DNS Operator Subscription
# Part of Red Hat Connectivity Link (RHCL) - manages DNS for inference endpoints
# Ref: https://docs.redhat.com/en/documentation/red_hat_connectivity_link/
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dns-operator
  namespace: openshift-dns-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: dns-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

