# MinIO Bucket Initialization Job
# Creates buckets and RHOAI service account for Data Connections
#
# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.0/html-single/managing_resources/index#using-connections
# Pattern: https://github.com/rhoai-genaiops/deploy-lab
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: minio-storage
  annotations:
    # Run AFTER MinIO Deployment is ready (Deployment is sync-wave: 3)
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: minio-init
    spec:
      restartPolicy: OnFailure
      # OpenShift 4.20 restricted-v2 SCC compliance
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mc
          image: quay.io/minio/mc:latest
          # OpenShift SCC requirements
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
            # mc needs a writable config directory (not /root/.mc)
            - name: MC_CONFIG_DIR
              value: /tmp/.mc
          envFrom:
            - secretRef:
                name: minio-credentials
          command:
            - /bin/sh
            - -ce
            - |
              mkdir -p /tmp/.mc
              
              # ═══════════════════════════════════════════════════════════════════
              # 1. Wait for MinIO service to be reachable (AWS can take 30-60s)
              # ═══════════════════════════════════════════════════════════════════
              echo "Waiting for MinIO at http://minio.minio-storage.svc:9000..."
              until curl -sf http://minio.minio-storage.svc:9000/minio/health/live; do
                echo "MinIO is unavailable - sleeping 5s..."
                sleep 5
              done
              echo "MinIO is ready!"
              
              # ═══════════════════════════════════════════════════════════════════
              # 2. Configure the mc alias
              # ═══════════════════════════════════════════════════════════════════
              echo "Configuring MinIO alias..."
              mc alias set myminio http://minio.minio-storage.svc:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
              
              # ═══════════════════════════════════════════════════════════════════
              # 3. Create buckets for RHOAI workloads
              # ═══════════════════════════════════════════════════════════════════
              echo "Creating buckets..."
              mc mb --ignore-existing myminio/rhoai-storage
              mc mb --ignore-existing myminio/models
              mc mb --ignore-existing myminio/pipelines
              
              # ═══════════════════════════════════════════════════════════════════
              # 4. Create RHOAI service account (for Data Connections)
              # ═══════════════════════════════════════════════════════════════════
              # This creates a dedicated access key for RHOAI workloads
              # The Data Connection Secret in private-ai uses these credentials
              echo "Creating RHOAI service account..."
              mc admin user add myminio ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} || echo "User already exists"
              mc admin policy attach myminio readwrite --user ${AWS_ACCESS_KEY_ID} || echo "Policy already attached"
              
              # ═══════════════════════════════════════════════════════════════════
              # 5. Verify setup
              # ═══════════════════════════════════════════════════════════════════
              echo ""
              echo "=== MinIO Initialization Complete ==="
              mc admin info myminio
              echo ""
              echo "Buckets:"
              mc ls myminio
              echo ""
              echo "Users:"
              mc admin user list myminio
