apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
  namespace: minio-storage
  annotations:
    # Same sync-wave as Deployment - PVC uses WaitForFirstConsumer binding mode
    argocd.argoproj.io/sync-wave: "3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi

