# =============================================================================
# GPU Switchboard Workbench
# =============================================================================
# Pre-configured workbench for the GPU-as-a-Service demo.
# Aligned with RHOAI 3.0 Dashboard-created notebook pattern.
#
# Features:
#   - No GPU required (CPU-only for admin tasks)
#   - Pre-loaded with GPU-Switchboard.ipynb via ConfigMap
#   - Uses cpu-small HardwareProfile
# =============================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpu-switchboard-storage
  namespace: private-ai
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    openshift.io/display-name: gpu-switchboard-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: gpu-switchboard
  namespace: private-ai
  labels:
    app: gpu-switchboard
    kueue.x-k8s.io/queue-name: default
    opendatahub.io/dashboard: "true"
    opendatahub.io/odh-managed: "true"
    opendatahub.io/user: ai-3aadmin
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    notebooks.opendatahub.io/inject-auth: "true"
    notebooks.opendatahub.io/last-image-selection: s2i-generic-data-science-notebook:2025.2
    notebooks.opendatahub.io/last-image-version-git-commit-selection: d3137ca
    notebooks.opendatahub.io/last-size-selection: ""
    opendatahub.io/accelerator-name: ""
    opendatahub.io/accelerator-profile-namespace: ""
    opendatahub.io/connections: ""
    opendatahub.io/hardware-profile-name: cpu-small
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/image-display-name: "Jupyter | Data Science | CPU | Python 3.12"
    opendatahub.io/username: ai-admin
    opendatahub.io/workbench-image-namespace: ""
    openshift.io/description: "Interactive notebook for GPU-as-a-Service demo - control 5 models with toggle switches"
    openshift.io/display-name: "GPU Switchboard"
spec:
  template:
    spec:
      enableServiceLinks: false
      serviceAccountName: gpu-switchboard
      containers:
        - name: gpu-switchboard
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2025.2
          imagePullPolicy: Always
          workingDir: /opt/app-root/src
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                            --ServerApp.token=''
                            --ServerApp.password=''
                            --ServerApp.base_url=/notebook/private-ai/gpu-switchboard
                            --ServerApp.quit_button=False
            - name: JUPYTER_IMAGE
              value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2025.2
            - name: PIP_CERT
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: REQUESTS_CA_BUNDLE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: SSL_CERT_FILE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: PIPELINES_SSL_SA_CERTS
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: KF_PIPELINES_SSL_SA_CERTS
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: GIT_SSL_CAINFO
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 8Gi
          livenessProbe:
            httpGet:
              path: /notebook/private-ai/gpu-switchboard/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /notebook/private-ai/gpu-switchboard/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: gpu-switchboard-storage
              mountPath: /opt/app-root/src/
            - name: shm
              mountPath: /dev/shm
            - name: trusted-ca
              mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
              subPath: ca-bundle.crt
              readOnly: true
            - name: runtime-images
              mountPath: /opt/app-root/pipeline-runtimes/
            # Pre-loaded notebook from ConfigMap
            - name: gpu-switchboard-notebook
              mountPath: /opt/app-root/src/GPU-Switchboard.ipynb
              subPath: GPU-Switchboard.ipynb
      volumes:
        - name: gpu-switchboard-storage
          persistentVolumeClaim:
            claimName: gpu-switchboard-storage
        - name: shm
          emptyDir:
            medium: Memory
        - name: trusted-ca
          configMap:
            name: workbench-trusted-ca-bundle
            optional: true
            items:
              - key: ca-bundle.crt
                path: ca-bundle.crt
        - name: runtime-images
          configMap:
            name: pipeline-runtime-images
            optional: true
        - name: gpu-switchboard-notebook
          configMap:
            name: gpu-switchboard-notebook
