apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: rhoai3-demo
      demo.rhoai.io/stage: "250"

resources:
  - project/base
  - rhoai-dsc/base
  - postgresql/base
  - storage/base
  - pipelines/base
  - mlflow/base
  - maas-proxy/base
  - evalhub/base
  - lmeval/base
  - dashboard/base

transformers:
  - transformers/odhapplication-dashboard-labels.yaml
