# HardwareProfile - GPU Profile for Model Serving
# Ref: https://rhpds.github.io/redhat-openshift-ai-3-showroom/modules/03-02-hardware-profile.html
# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.0/html-single/working_with_accelerators/index#working-with-hardware-profiles
apiVersion: infrastructure.opendatahub.io/v1alpha1
kind: HardwareProfile
metadata:
  name: gpu-profile
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "16"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  identifiers:
    # CPU allocation
    - identifier: cpu
      displayName: CPU
      resourceType: CPU
      minCount: 1
      maxCount: "8"
      defaultCount: "1"
    
    # Memory allocation
    - identifier: memory
      displayName: Memory
      resourceType: Memory
      minCount: 1Gi
      maxCount: 16Gi
      defaultCount: 12Gi
    
    # GPU allocation (NVIDIA L4 on AWS G6 instances)
    - identifier: nvidia.com/gpu
      displayName: GPU
      resourceType: Accelerator
      minCount: 1
      maxCount: 4
      defaultCount: 1

