# HardwareProfile - NVIDIA L4 4GPUs (AWS g6.12xlarge)
# Global profile with Queue-based scheduling for Kueue integration
# Node specs: 48 vCPU, 192 GB RAM, 4x NVIDIA L4 GPU
apiVersion: infrastructure.opendatahub.io/v1
kind: HardwareProfile
metadata:
  name: nvidia-l4-4gpu
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "16"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    opendatahub.io/display-name: "NVIDIA L4 4GPUs"
    opendatahub.io/description: "AWS g6.12xlarge - Multi-GPU for distributed inference"
    opendatahub.io/disabled: "false"
  labels:
    app.kubernetes.io/part-of: hardwareprofile
    app.opendatahub.io/hardwareprofile: "true"
spec:
  # Queue-based scheduling - Kueue handles node selection via ResourceFlavors
  scheduling:
    type: Queue
    kueue:
      localQueueName: default
  identifiers:
    - identifier: cpu
      displayName: CPU
      resourceType: CPU
      minCount: 1
      maxCount: 46
      defaultCount: 24
    - identifier: memory
      displayName: Memory
      resourceType: Memory
      minCount: 8Gi
      maxCount: 180Gi
      defaultCount: 96Gi
    - identifier: nvidia.com/gpu
      displayName: NVIDIA L4 GPU
      resourceType: Accelerator
      minCount: 1
      maxCount: 4
      defaultCount: 4
