# HardwareProfile - Small CPU-only (Global, Queue-based)
# Works with any Kueue-managed project that has a LocalQueue named "default"
apiVersion: infrastructure.opendatahub.io/v1
kind: HardwareProfile
metadata:
  name: cpu-small
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "16"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    opendatahub.io/display-name: "Small (CPU Only)"
    opendatahub.io/description: "CPU-only for development and testing"
    opendatahub.io/disabled: "false"
  labels:
    app.kubernetes.io/part-of: hardwareprofile
    app.opendatahub.io/hardwareprofile: "true"
spec:
  # Queue-based scheduling - requires LocalQueue named "default" in user project
  scheduling:
    type: Queue
    kueue:
      localQueueName: default
  identifiers:
    - identifier: cpu
      displayName: CPU
      resourceType: CPU
      minCount: 1
      maxCount: 4
      defaultCount: 2
    - identifier: memory
      displayName: Memory
      resourceType: Memory
      minCount: 1Gi
      maxCount: 8Gi
      defaultCount: 4Gi
