# HardwareProfile - Default (NVIDIA L4 1GPU / AWS g6.4xlarge)
# Overrides the operator-created default-profile with GPU-enabled settings
# Node specs: 16 vCPU, 64 GB RAM, 1x NVIDIA L4 GPU
apiVersion: infrastructure.opendatahub.io/v1
kind: HardwareProfile
metadata:
  name: default-profile
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "16"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    opendatahub.io/display-name: "NVIDIA L4 1GPU (Default)"
    opendatahub.io/description: "AWS g6.4xlarge - Single NVIDIA L4 GPU for inference workloads (Default profile)"
    opendatahub.io/disabled: "false"
    opendatahub.io/managed: "false"
  labels:
    app.kubernetes.io/part-of: hardwareprofile
    app.opendatahub.io/hardwareprofile: "true"
spec:
  # Scheduling - target g6.4xlarge nodes
  scheduling:
    type: Node
    node:
      nodeSelector:
        node-role.kubernetes.io/gpu: ""
        node.kubernetes.io/instance-type: g6.4xlarge
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
  
  # Resource identifiers (matching g6.4xlarge specs)
  identifiers:
    # CPU: g6.4xlarge has 16 vCPU
    - identifier: cpu
      displayName: CPU
      resourceType: CPU
      minCount: 1
      maxCount: "16"
      defaultCount: "8"
    
    # Memory: g6.4xlarge has 64 GB
    - identifier: memory
      displayName: Memory
      resourceType: Memory
      minCount: 4Gi
      maxCount: 64Gi
      defaultCount: 32Gi
    
    # GPU: g6.4xlarge has 1x NVIDIA L4
    - identifier: nvidia.com/gpu
      displayName: NVIDIA L4 GPU
      resourceType: Accelerator
      minCount: 1
      maxCount: 1
      defaultCount: 1

