apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maas-postgres-data
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 5Gi
