# Subscription for RHOAI Operator
# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2/html/installing_and_uninstalling_openshift_ai_self-managed/index
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  name: rhods-operator
  channel: stable-2.20
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

