apiVersion: v1
kind: Service
metadata:
  name: maas-internal-proxy
  namespace: enterprise-rag
  labels:
    app.kubernetes.io/part-of: rag
    app.kubernetes.io/name: maas-internal-proxy
    app.kubernetes.io/component: maas-egress
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: maas-internal-proxy
