apiVersion: v1
kind: Service
metadata:
  name: private-rag-postgres
  namespace: enterprise-rag
  labels:
    app.kubernetes.io/part-of: rag
    app.kubernetes.io/name: private-rag-postgres
    app.kubernetes.io/component: database
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: postgresql
  selector:
    app.kubernetes.io/name: private-rag-postgres
