# User Workload Monitoring Config
# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.3/html/managing_and_monitoring_models/managing_and_monitoring_models#configuring-monitoring-for-the-model-serving-platform
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  config.yaml: |
    prometheus:
      logLevel: debug
      retention: 15d
