# =============================================================================
# LlamaStackDistribution - GenAI Playground Backend
# =============================================================================
# The LlamaStackDistribution CR orchestrates the GenAI Playground backend.
# It translates UI actions into vLLM API calls and manages:
#   - Model inference routing
#   - RAG (vector_io with Milvus)
#   - MCP servers for tool calling
#   - Session/agent state management
#
# STATUS: Technology Preview (TP) in RHOAI 3.0
# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.0/html-single/experimenting_with_models_in_the_gen_ai_playground/index
#
# CRD Verification:
#   oc get crd llamastackdistributions.llamastack.io
#   oc explain llamastackdistribution.spec
#
# =============================================================================
apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: lsd-genai-playground
  namespace: private-ai
  labels:
    opendatahub.io/dashboard: "true"
    app.kubernetes.io/name: llamastack
    app.kubernetes.io/part-of: private-ai-platform
    app.kubernetes.io/component: playground-backend
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    openshift.io/display-name: lsd-genai-playground
spec:
  replicas: 1
  server:
    # Distribution: Red Hat's pre-built LlamaStack distribution
    distribution:
      name: rh-dev
    
    # Container configuration
    containerSpec:
      name: llama-stack
      port: 8321
      command:
        - /bin/sh
        - -c
        - llama stack run /etc/llama-stack/run.yaml
      env:
        # TLS verification disabled for internal cluster communication
        - name: VLLM_TLS_VERIFY
          value: "false"
        # Milvus database path for RAG vector storage
        - name: MILVUS_DB_PATH
          value: ~/.llama/milvus.db
        # FMS orchestrator (not used in basic setup)
        - name: FMS_ORCHESTRATOR_URL
          value: http://localhost
        # Max tokens sent to vLLM (must be < model's --max-model-len)
        - name: VLLM_MAX_TOKENS
          value: "4096"
        # API token for vLLM authentication (not enforced in this demo)
        - name: VLLM_API_TOKEN_1
          value: fake
        # Config directory for LlamaStack
        - name: LLAMA_STACK_CONFIG_DIR
          value: /opt/app-root/src/.llama/distributions/rh/
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: "2"
          memory: 12Gi
    
    # User-provided configuration (run.yaml)
    userConfig:
      configMapName: llama-stack-config
---
# =============================================================================
# LlamaStack Configuration (run.yaml)
# =============================================================================
# This ConfigMap contains the LlamaStack run.yaml that defines:
#   - Inference providers (vLLM endpoints)
#   - Vector I/O providers (Milvus for RAG)
#   - Tool runtimes (RAG, MCP)
#   - Model registrations
#
# The Dashboard will update this ConfigMap when models are added/removed
# from the Playground configuration.
# =============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-stack-config
  namespace: private-ai
  labels:
    llamastack.io/distribution: lsd-genai-playground
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: Replace=true
data:
  run.yaml: |
    # Llama Stack Configuration
    version: "2"
    image_name: rh
    apis:
    - agents
    - datasetio
    - files
    - inference
    - safety
    - scoring
    - tool_runtime
    - vector_io
    providers:
      inference:
      # Embedding model for RAG
      - provider_id: sentence-transformers
        provider_type: inline::sentence-transformers
        config: {}
      # vLLM Inference Provider 1: Mistral-3 INT4 (1-GPU)
      - provider_id: vllm-inference-1
        provider_type: remote::vllm
        config:
          api_token: ${env.VLLM_API_TOKEN_1:=fake}
          max_tokens: ${env.VLLM_MAX_TOKENS:=4096}
          tls_verify: ${env.VLLM_TLS_VERIFY:=true}
          url: http://mistral-3-int4-predictor.private-ai.svc.cluster.local:8080/v1
      # vLLM Inference Provider 2: Devstral-2 (4-GPU Agentic)
      - provider_id: vllm-inference-2
        provider_type: remote::vllm
        config:
          api_token: ${env.VLLM_API_TOKEN_1:=fake}
          max_tokens: ${env.VLLM_MAX_TOKENS:=4096}
          tls_verify: ${env.VLLM_TLS_VERIFY:=true}
          url: http://devstral-2-predictor.private-ai.svc.cluster.local:8080/v1
      vector_io:
      - provider_id: milvus
        provider_type: inline::milvus
        config:
          db_path: /opt/app-root/src/.llama/distributions/rh/milvus.db
          kvstore:
            db_path: /opt/app-root/src/.llama/distributions/rh/milvus_registry.db
            namespace: null
            type: sqlite
      agents:
      - provider_id: meta-reference
        provider_type: inline::meta-reference
        config:
          persistence_store:
            db_path: /opt/app-root/src/.llama/distributions/rh/agents_store.db
            namespace: null
            type: sqlite
          responses_store:
            db_path: /opt/app-root/src/.llama/distributions/rh/responses_store.db
            type: sqlite
      eval: []
      files:
      - provider_id: meta-reference-files
        provider_type: inline::localfs
        config:
          metadata_store:
            db_path: /opt/app-root/src/.llama/distributions/rh/files_metadata.db
            type: sqlite
          storage_dir: /opt/app-root/src/.llama/distributions/rh/files
      datasetio:
      - provider_id: huggingface
        provider_type: remote::huggingface
        config:
          kvstore:
            db_path: /opt/app-root/src/.llama/distributions/rh/huggingface_datasetio.db
            namespace: null
            type: sqlite
      scoring:
      - provider_id: basic
        provider_type: inline::basic
        config: {}
      - provider_id: llm-as-judge
        provider_type: inline::llm-as-judge
        config: {}
      tool_runtime:
      - provider_id: rag-runtime
        provider_type: inline::rag-runtime
        config: {}
      - provider_id: model-context-protocol
        provider_type: remote::model-context-protocol
        config: {}
    metadata_store:
      type: sqlite
      db_path: /opt/app-root/src/.llama/distributions/rh/inference_store.db
    models:
    # Embedding model for RAG
    - provider_id: sentence-transformers
      model_id: granite-embedding-125m
      provider_model_id: ibm-granite/granite-embedding-125m-english
      model_type: embedding
      metadata:
        embedding_dimension: 768
    # LLM Model 1: Mistral-3 INT4 (1-GPU)
    - provider_id: vllm-inference-1
      model_id: mistral-3-int4
      model_type: llm
      metadata:
        description: "Mistral Small 24B INT4 quantized - efficient inference on 1 GPU"
        display_name: Mistral-3 INT4 (1-GPU)
    # LLM Model 2: Devstral-2 (4-GPU Agentic)
    - provider_id: vllm-inference-2
      model_id: devstral-2
      model_type: llm
      metadata:
        description: "Devstral-2 with tool calling - optimized for agentic workloads"
        display_name: Devstral-2 (4-GPU Agentic)
    shields: []
    vector_dbs: []
    datasets: []
    scoring_fns: []
    benchmarks: []
    tool_groups:
    - toolgroup_id: builtin::rag
      provider_id: rag-runtime
    server:
      port: 8321
