apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: rhoai3-demo
    demo.rhoai.io/stage: "110"
    openshift.io/cluster-monitoring: "true"

