apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount-postgres.yaml
  - configmap-postgres-init.yaml
  - service-postgres.yaml
  - statefulset-postgres.yaml
  - service-docling.yaml
  - deployment-docling.yaml
  - llamastackdistribution-private-rag.yaml
