apiVersion: maas.opendatahub.io/v1alpha1
kind: ExternalModel
metadata:
  name: gpt-5.4-nano
  namespace: models-as-a-service
  labels:
    app.kubernetes.io/name: gpt-5.4-nano
    app.kubernetes.io/component: external-model
    demo.rhoai.io/provider: openai
  annotations:
    argocd.argoproj.io/sync-wave: "16"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider: openai
  endpoint: api.openai.com
  targetModel: gpt-5.4-nano
  credentialRef:
    name: openai-provider-api-key
---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: gpt-5.4-nano
  namespace: models-as-a-service
  labels:
    app.kubernetes.io/name: gpt-5.4-nano
    app.kubernetes.io/component: maas-model-ref
    demo.rhoai.io/provider: openai
  annotations:
    argocd.argoproj.io/sync-wave: "17"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  modelRef:
    kind: ExternalModel
    name: gpt-5.4-nano
