# MariaDB Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-registry-db-pvc
  namespace: private-ai
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    # Skip health check - PVC uses WaitForFirstConsumer
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3-csi
