apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: private-rag-milvus-data
  namespace: enterprise-rag
  labels:
    app.kubernetes.io/part-of: rag
    app.kubernetes.io/name: private-rag-milvus
    app.kubernetes.io/component: database
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
