# Ref: https://grafana.github.io/grafana-operator/docs/grafana/
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: private-ai
  labels:
    app: grafana
    dashboards: "grafana"
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: observability
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  # instanceSelector on GrafanaDashboard/GrafanaDatasource CRs matches dashboards: "grafana" label
  route:
    spec:
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
  deployment:
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: grafana
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
  config:
    log:
      mode: "console"
      level: "info"
    auth.anonymous:
      enabled: "true"
      org_role: "Admin"
    
    auth:
      disable_login_form: "true"
      disable_signout_menu: "true"
    server:
      root_url: "%(protocol)s://%(domain)s/"
    security:
      allow_embedding: "true"

