apiVersion: v1
kind: Namespace
metadata:
  name: edge-ai-demo
  labels:
    app.kubernetes.io/part-of: edge-ai
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: "Edge AI Demo (SNO simulation)"
