# Custom Metrics Autoscaler OperatorGroup
# Based on: https://github.com/redhat-cop/gitops-catalog/tree/main/openshift-custom-metrics-autoscaler
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-keda
  namespace: openshift-keda
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec: {}

