apiVersion: mlflow.kubeflow.org/v1
kind: MLflowConfig
metadata:
  name: mlflow
  namespace: enterprise-rag
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/component: mlflow
    app.kubernetes.io/part-of: model-evaluation
spec:
  artifactRootSecret: mlflow-artifact-connection
  artifactRootPath: enterprise-rag/rag-evaluation
