# LiteLLM Secret
apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
  namespace: litemaas
  labels:
    app: litellm
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  LITELLM_MASTER_KEY: sk-1b4f0a05549af06f80db6cd51b37fd01
  UI_USERNAME: admin
  UI_PASSWORD: LiteMaaS2024!
---
# LiteLLM Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litemaas
  labels:
    app: litellm
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  config.yaml: |
    # LiteLLM Proxy Configuration for LiteMaaS
    # Routes requests to vLLM models in private-ai namespace
    
    model_list:
      # Mistral-3 INT4 - Primary chat model (always running)
      - model_name: mistral-3-int4
        litellm_params:
          model: openai/mistral-3-int4
          api_base: http://mistral-3-int4-predictor.private-ai.svc.cluster.local:8080/v1
          api_key: "none"
          
      # Granite-8B Agent - Agentic tool-calling model
      - model_name: granite-8b-agent
        litellm_params:
          model: openai/granite-8b-agent
          api_base: http://granite-8b-agent-predictor.private-ai.svc.cluster.local:8080/v1
          api_key: "none"
          
      # Mistral-3 BF16 - High-quality enterprise model (4-GPU)
      - model_name: mistral-3-bf16
        litellm_params:
          model: openai/mistral-3-bf16
          api_base: http://mistral-3-bf16-predictor.private-ai.svc.cluster.local:8080/v1
          api_key: "none"
          
      # Devstral-2 - Agentic coding assistant (4-GPU)
      - model_name: devstral-2
        litellm_params:
          model: openai/devstral-2
          api_base: http://devstral-2-predictor.private-ai.svc.cluster.local:8080/v1
          api_key: "none"
          
      # GPT-OSS-20B - Complex reasoning (4-GPU)
      - model_name: gpt-oss-20b
        litellm_params:
          model: openai/gpt-oss-20b
          api_base: http://gpt-oss-20b-predictor.private-ai.svc.cluster.local:8080/v1
          api_key: "none"
    
    litellm_settings:
      drop_params: true
      set_verbose: true
      request_timeout: 300
      num_retries: 2
    
    general_settings:
      master_key: sk-1b4f0a05549af06f80db6cd51b37fd01
---
# LiteLLM Service
apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: litemaas
  labels:
    app: litellm
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: litellm
  type: ClusterIP
---
# LiteLLM Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: litemaas
  labels:
    app: litellm
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
        app.kubernetes.io/part-of: litemaas
    spec:
      containers:
        - name: litellm
          image: ghcr.io/berriai/litellm:main-v1.56.4
          args:
            - --config
            - /app/config.yaml
            - --port
            - "4000"
          ports:
            - containerPort: 4000
              name: http
          envFrom:
            - secretRef:
                name: litellm-secret
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: litellm-config
---
# LiteLLM Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: litellm
  namespace: litemaas
  labels:
    app: litellm
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  host: litellm-litemaas.apps.cluster-78cqq.78cqq.sandbox3352.opentlc.com
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: litellm
    weight: 100

