# LiteLLM Secret
# Based on official LiteMaaS deployment
# Ref: https://github.com/rh-aiservices-bu/litemaas/tree/main/deployment/openshift
apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
  namespace: litemaas
  labels:
    app: litellm
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  # Password must match postgres-secret POSTGRESQL_PASSWORD
  database-url: postgresql://litemaas_admin:LiteMaaS2024SecurePass@postgres:5432/litemaas_db
  master-key: sk-1b4f0a05549af06f80db6cd51b37fd01
  ui-username: admin
  ui-password: LiteMaaS2024!
---
# LiteLLM Config - models will be stored in DB via STORE_MODEL_IN_DB
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litemaas
  labels:
    app: litellm
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  # Models are stored in the database, not in a config file
  # This ConfigMap is kept for any future static config needs
  placeholder: "Models are managed via STORE_MODEL_IN_DB=True"
---
# LiteLLM Service
apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: litemaas
  labels:
    app: litellm
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: litellm
  type: ClusterIP
---
# LiteLLM Deployment
# Based on official LiteMaaS deployment pattern
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: litemaas
  labels:
    app: litellm
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
        app.kubernetes.io/part-of: litemaas
    spec:
      initContainers:
        # Wait for database to be ready before starting LiteLLM
        - name: wait-for-database
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              until psql "$DATABASE_URL" -c '\q' 2>/dev/null; do
                echo "Waiting for database..."
                sleep 2
              done
              echo "Database is ready!"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: litellm-secret
                  key: database-url
      containers:
        - name: litellm
          # Official LiteMaaS uses litellm-non_root image with database support
          image: ghcr.io/berriai/litellm-non_root:main-v1.74.7-stable
          ports:
            - containerPort: 4000
              name: http
          env:
            # Database Configuration
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: litellm-secret
                  key: database-url
            # LiteLLM Configuration
            - name: LITELLM_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: litellm-secret
                  key: master-key
            - name: UI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: litellm-secret
                  key: ui-username
            - name: UI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: litellm-secret
                  key: ui-password
            # Store models in database for dynamic management
            - name: STORE_MODEL_IN_DB
              value: "True"
            - name: LITELLM_MODE
              value: "PRODUCTION"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 4000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
# LiteLLM Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: litellm
  namespace: litemaas
  labels:
    app: litellm
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  host: litellm-litemaas.apps.cluster-78cqq.78cqq.sandbox3352.opentlc.com
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: litellm
    weight: 100
