apiVersion: v1
kind: ServiceAccount
metadata:
  name: nemo-guardrails-sa
  namespace: ai-safety
  labels:
    app.kubernetes.io/part-of: guardrails
    app.kubernetes.io/name: nemo-guardrails-sa
    app.kubernetes.io/component: safety
  annotations:
    argocd.argoproj.io/sync-wave: "3"
