# Database Credentials Secret for ModelRegistry
# Located in rhoai-model-registries namespace (where the registry lives)
#
# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.0/html-single/managing_model_registries/index
apiVersion: v1
kind: Secret
metadata:
  name: private-ai-registry-db-creds
  namespace: rhoai-model-registries
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
type: Opaque
stringData:
  # Must match the credentials in private-ai namespace MariaDB
  database-name: model_registry
  database-user: mlmd
  database-password: mlmd-secret-123
