# ModelRegistry Custom Resource
# Centralized model versioning and metadata management
#
# IMPORTANT: Registry instances go in the `rhoai-model-registries` namespace,
# not redhat-ods-applications. The operator manages this namespace.
#
# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.0/html-single/managing_model_registries/index
apiVersion: modelregistry.opendatahub.io/v1beta1
kind: ModelRegistry
metadata:
  name: private-ai-registry
  namespace: rhoai-model-registries
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    openshift.io/display-name: "Private AI Registry"
    openshift.io/description: "Model registry for the Private AI project - GPU-as-a-Service demo"
spec:
  # ═══════════════════════════════════════════════════════════════════════════
  # gRPC Configuration (internal model metadata API)
  # ═══════════════════════════════════════════════════════════════════════════
  grpc:
    port: 9090
  
  # ═══════════════════════════════════════════════════════════════════════════
  # REST API Configuration
  # ═══════════════════════════════════════════════════════════════════════════
  rest:
    port: 8080
    serviceRoute: disabled  # Use kubeRBACProxy route instead
  
  # ═══════════════════════════════════════════════════════════════════════════
  # Kube RBAC Proxy (authentication/authorization)
  # ═══════════════════════════════════════════════════════════════════════════
  kubeRBACProxy:
    port: 8443
    routePort: 443
    serviceRoute: enabled
  
  # ═══════════════════════════════════════════════════════════════════════════
  # Database Configuration (MariaDB in private-ai namespace)
  # ═══════════════════════════════════════════════════════════════════════════
  mysql:
    host: model-registry-db.private-ai.svc.cluster.local
    port: 3306
    database: model_registry
    username: mlmd
    skipDBCreation: false
    passwordSecret:
      name: private-ai-registry-db-creds
      key: database-password
