# S3 Credentials Secret for ModelRegistry Artifact Storage
# Links to MinIO deployed in Step 03
apiVersion: v1
kind: Secret
metadata:
  name: private-ai-registry-s3-creds
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
stringData:
  # Must match the credentials from Step 03 MinIO
  AWS_ACCESS_KEY_ID: rhoai-access-key
  AWS_SECRET_ACCESS_KEY: rhoai-secret-key-12345

