# Can manage the enterprise demo project resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-admin-admin
  namespace: maas
  annotations:
    argocd.argoproj.io/sync-wave: "5"
subjects:
  - kind: User
    name: ai-admin
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-admin-admin
  namespace: enterprise-rag
  annotations:
    argocd.argoproj.io/sync-wave: "5"
subjects:
  - kind: User
    name: ai-admin
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-admin-admin
  namespace: enterprise-mlops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
subjects:
  - kind: User
    name: ai-admin
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
