apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-enterprise-rag.yaml
  - localqueue-cpu-default.yaml
  - rolebinding-developer-edit.yaml
  - rolebinding-admins-admin.yaml
  - obc-enterprise-rag.yaml
