apiVersion: v1
kind: Namespace
metadata:
  name: enterprise-rag
  labels:
    opendatahub.io/dashboard: "true"
    kubernetes.io/metadata.name: enterprise-rag
    app.kubernetes.io/part-of: rag
    app.kubernetes.io/name: enterprise-rag
    app.kubernetes.io/component: namespace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: "Enterprise RAG"
    openshift.io/description: "Private enterprise knowledge and retrieval-augmented generation demo project."
