apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: enterprise-rag-bucket
  namespace: enterprise-rag
  labels:
    app.kubernetes.io/name: enterprise-rag-bucket
    app.kubernetes.io/component: private-rag-documents
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generateBucketName: enterprise-rag
  storageClassName: openshift-storage.noobaa.io
