# ClusterPolicy configures NVIDIA GPU Operator components
# Ref: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/openshift/contents.html
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  operator:
    defaultRuntime: crio
    use_ocp_driver_toolkit: true
  
  daemonsets:
    updateStrategy: RollingUpdate
    rollingUpdate:
      maxUnavailable: "1"
  
  driver:
    enabled: true
  
  dcgm:
    enabled: true
  
  dcgmExporter:
    enabled: true
    serviceMonitor:
      enabled: true
  
  devicePlugin:
    enabled: true
  
  gfd:
    enabled: true
  
  migManager:
    enabled: true
  
  nodeStatusExporter:
    enabled: true
  
  toolkit:
    enabled: true

