apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ensure-cert-manager.yaml
  - patch-gateway-hostname.yaml
  - configure-kuadrant.yaml
  - restart-kserve-controllers.yaml
