# IMPORTANT: Community Operator - not vetted by Red Hat, no Red Hat support.
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: grafana-operator
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: observability
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: v5
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace

