# ═══════════════════════════════════════════════════════════════════════════════
# LiteMaaS Application - Backend + Frontend
# ═══════════════════════════════════════════════════════════════════════════════
# Self-service MaaS platform with:
# - API key management
# - Subscription management  
# - Usage tracking & analytics
# - Budget controls
#
# Ref: https://github.com/rh-aiservices-bu/litemaas
# ═══════════════════════════════════════════════════════════════════════════════
---
apiVersion: v1
kind: Secret
metadata:
  name: litemaas-config
  namespace: litemaas
  labels:
    app.kubernetes.io/name: litemaas
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
stringData:
  # JWT configuration
  JWT_SECRET: litemaas-jwt-secret-demo-2024-change-in-production
  JWT_EXPIRES_IN: 24h
  
  # LiteLLM connection
  LITELLM_URL: http://litellm:4000
  LITELLM_MASTER_KEY: sk-litemaas-demo-key-2024
  
  # OAuth2 configuration (OpenShift)
  # These will be populated by the deploy.sh script
  OAUTH_CLIENT_ID: litemaas
  OAUTH_CLIENT_SECRET: placeholder-update-after-oauth-setup
  
  # Admin configuration
  ADMIN_GROUPS: cluster-admins,litemaas-admins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litemaas-backend
  namespace: litemaas
  labels:
    app.kubernetes.io/name: litemaas-backend
    app.kubernetes.io/part-of: litemaas
    app.kubernetes.io/component: backend
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: litemaas-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: litemaas-backend
        app.kubernetes.io/part-of: litemaas
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: quay.io/rh-aiservices-bu/litemaas-backend:0.1.2
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8081"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: litemaas-config
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: litemaas-config
                  key: JWT_EXPIRES_IN
            - name: LITELLM_URL
              valueFrom:
                secretKeyRef:
                  name: litemaas-config
                  key: LITELLM_URL
            - name: LITELLM_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: litemaas-config
                  key: LITELLM_MASTER_KEY
            - name: ADMIN_GROUPS
              valueFrom:
                secretKeyRef:
                  name: litemaas-config
                  key: ADMIN_GROUPS
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: litemaas-backend
  namespace: litemaas
  labels:
    app.kubernetes.io/name: litemaas-backend
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  selector:
    app.kubernetes.io/name: litemaas-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litemaas-frontend
  namespace: litemaas
  labels:
    app.kubernetes.io/name: litemaas-frontend
    app.kubernetes.io/part-of: litemaas
    app.kubernetes.io/component: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: litemaas-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: litemaas-frontend
        app.kubernetes.io/part-of: litemaas
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: quay.io/rh-aiservices-bu/litemaas-frontend:0.1.2
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: production
            - name: REACT_APP_API_URL
              value: /api
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: litemaas-frontend
  namespace: litemaas
  labels:
    app.kubernetes.io/name: litemaas-frontend
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app.kubernetes.io/name: litemaas-frontend
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: litemaas
  namespace: litemaas
  labels:
    app.kubernetes.io/name: litemaas
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    # Proxy /api requests to backend
    haproxy.router.openshift.io/rewrite-target: /
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: litemaas-frontend
  port:
    targetPort: http
---
# API route - proxies /api to backend
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: litemaas-api
  namespace: litemaas
  labels:
    app.kubernetes.io/name: litemaas-api
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  path: /api
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: litemaas-backend
  port:
    targetPort: http

