apiVersion: v1
kind: ServiceAccount
metadata:
  name: evalhub-jobs
  namespace: model-evaluation
  labels:
    app.kubernetes.io/part-of: evaluation
    app.kubernetes.io/name: evalhub-jobs
    app.kubernetes.io/component: evaluation
  annotations:
    argocd.argoproj.io/sync-wave: "4"
