apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: private-rag-chatbot
  namespace: enterprise-rag
  labels:
    app.kubernetes.io/name: private-rag-chatbot
    app.kubernetes.io/component: chatbot-ui
    app.kubernetes.io/part-of: rag
  annotations:
    argocd.argoproj.io/sync-wave: "20"
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: private-rag-chatbot
  namespace: enterprise-rag
  labels:
    app.kubernetes.io/name: private-rag-chatbot
    app.kubernetes.io/component: chatbot-ui
    app.kubernetes.io/part-of: rag
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: private-rag-chatbot:latest
  triggers: []
