apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-build.yaml
  - build.yaml
  - configmap-chatbot.yaml
  - rbac.yaml
  - rolebinding-mlflow-chatbot.yaml
  - deployment-chatbot.yaml
  - service-chatbot.yaml
  - route-chatbot.yaml
  - consolelink-chatbot.yaml
  - cronjob-gpt-keepalive.yaml
