apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: private-rag-chatbot
  namespace: enterprise-rag
  labels:
    app.kubernetes.io/name: private-rag-chatbot
    app.kubernetes.io/component: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "31"
    haproxy.router.openshift.io/timeout: 600s
    openshift.io/display-name: Private RAG Chatbot
spec:
  to:
    kind: Service
    name: private-rag-chatbot
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
