apiVersion: v1
kind: Service
metadata:
  name: private-rag-chatbot
  namespace: enterprise-rag
  labels:
    app.kubernetes.io/name: private-rag-chatbot
    app.kubernetes.io/component: chatbot-ui
    app.kubernetes.io/part-of: rag
  annotations:
    argocd.argoproj.io/sync-wave: "22"
spec:
  selector:
    app.kubernetes.io/name: private-rag-chatbot
  ports:
    - name: http
      port: 8501
      targetPort: http
