apiVersion: v1
kind: Service
metadata:
  name: private-rag-chatbot
  namespace: enterprise-rag
  labels:
    app.kubernetes.io/name: private-rag-chatbot
    app.kubernetes.io/component: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  selector:
    app.kubernetes.io/name: private-rag-chatbot
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 8501
      targetPort: http
