# RoleBinding: ai-admin as Project Admin
# Can manage the private-ai project, view LocalQueue status, see all workloads
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-admin-admin
  namespace: private-ai
  annotations:
    argocd.argoproj.io/sync-wave: "5"
subjects:
  - kind: User
    name: ai-admin
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

