apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: private-rag-pipeline-workspace
  namespace: demo-sandbox
  labels:
    app.kubernetes.io/name: private-rag-pipeline-workspace
    app.kubernetes.io/component: pipeline-workspace
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 5Gi
