# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.4/html/managing_openshift_ai/managing-distributed-workloads_managing-rhoai
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: maas-gpu
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: maas
  resourceGroups:
    - coveredResources:
        - cpu
        - memory
        - nvidia.com/gpu
      flavors:
        - name: aws-l4
          resources:
            - name: cpu
              nominalQuota: "60"
            - name: memory
              nominalQuota: 240Gi
            - name: nvidia.com/gpu
              nominalQuota: "5"

