apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-pvc
  namespace: private-ai
  labels:
    app: milvus
    app.kubernetes.io/name: milvus
    app.kubernetes.io/component: vector-database
    app.kubernetes.io/part-of: rag-pipeline
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
