apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio-console
  namespace: minio-storage
  labels:
    app: minio
spec:
  to:
    kind: Service
    name: minio
  port:
    targetPort: console
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
