apiVersion: v1
kind: Namespace
metadata:
  name: ai-safety
  labels:
    opendatahub.io/dashboard: "true"
    kubernetes.io/metadata.name: ai-safety
    app.kubernetes.io/part-of: guardrails
    app.kubernetes.io/name: ai-safety
    app.kubernetes.io/component: namespace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: "AI Safety"
    openshift.io/description: "NeMo Guardrails safety controls and policy enforcement around governed GenAI models."
