apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-rhoai-model-registries.yaml
  - modelregistry-demo.yaml
  - rolebinding-demo-registry-admins.yaml
  - rolebinding-demo-registry-developers.yaml
