# Demo Workbench 1 - Gets the GPU first
# This workbench will be ADMITTED immediately if GPU is available
# Uses nvidia-l4-1gpu Hardware Profile for resource allocation
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: demo-workbench-1
  namespace: private-ai
  labels:
    app: demo-workbench-1
    opendatahub.io/dashboard: "true"
    opendatahub.io/odh-managed: "true"
    opendatahub.io/user: ai-developer
    # Kueue queue assignment (matches Hardware Profile's localQueueName)
    kueue.x-k8s.io/queue-name: "default"
  annotations:
    # RHOAI 3.0: Use inject-auth for kube-rbac-proxy sidecar
    notebooks.opendatahub.io/inject-auth: "true"
    # Hardware Profile reference (nvidia-l4-1gpu)
    opendatahub.io/hardware-profile-name: "nvidia-l4-1gpu"
    opendatahub.io/hardware-profile-namespace: "redhat-ods-applications"
    # Accelerator tracking
    opendatahub.io/accelerator-name: ""
    opendatahub.io/accelerator-profile-namespace: ""
    # Image selection - must match ImageStream annotations to avoid "deprecated" warning
    notebooks.opendatahub.io/last-image-selection: "pytorch:2025.2"
    notebooks.opendatahub.io/last-image-version-git-commit-selection: "8e73cac"
    opendatahub.io/image-display-name: "Jupyter | PyTorch | CUDA | Python 3.12"
    opendatahub.io/workbench-image-namespace: ""
    # User and display info
    opendatahub.io/username: "ai-developer"
    openshift.io/display-name: "Demo Workbench 1 (GPU)"
    openshift.io/description: "GPU-as-a-Service Demo - demonstrates GPU allocation via Kueue"
spec:
  template:
    spec:
      containers:
        - name: demo-workbench-1
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/pytorch:2025.2
          imagePullPolicy: Always
          # Resources from nvidia-l4-1gpu Hardware Profile defaults
          resources:
            limits:
              cpu: "8"
              memory: 32Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "8"
              memory: 32Gi
              nvidia.com/gpu: "1"
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          env:
            # RHOAI 3.0: MUST set base_url for path-based routing via Gateway API
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/private-ai/demo-workbench-1
                --ServerApp.quit_button=False
            - name: JUPYTER_IMAGE
              value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/pytorch:2025.2
          # Probes must use the base_url path
          livenessProbe:
            httpGet:
              path: /notebook/private-ai/demo-workbench-1/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /notebook/private-ai/demo-workbench-1/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: workbench-data
              mountPath: /opt/app-root/src
            - name: demo-notebooks
              mountPath: /opt/app-root/src/demo
              readOnly: true
            - name: shm
              mountPath: /dev/shm
          workingDir: /opt/app-root/src
      enableServiceLinks: false
      # Tolerate GPU node taints
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          value: "true"
          effect: NoSchedule
      # Target g6.4xlarge nodes (single L4 GPU)
      nodeSelector:
        node.kubernetes.io/instance-type: g6.4xlarge
      volumes:
        - name: workbench-data
          persistentVolumeClaim:
            claimName: demo-workbench-1-pvc
        - name: demo-notebooks
          configMap:
            name: gpu-demo-notebooks
        - name: shm
          emptyDir:
            medium: Memory
