# Demo Workbench 2 - Gets QUEUED (no GPU available)
# This workbench will be QUEUED because workbench-1 already has the GPU
# It will automatically start when workbench-1 is deleted
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: demo-workbench-2
  namespace: private-ai
  labels:
    app: demo-workbench-2
    opendatahub.io/dashboard: "true"
    # Same queue as workbench-1 - competing for same GPU quota
    kueue.x-k8s.io/queue-name: "private-ai-queue"
  annotations:
    notebooks.opendatahub.io/inject-oauth: "true"
    opendatahub.io/username: "ai-admin"
    openshift.io/display-name: "Demo Workbench 2 (Queued)"
    openshift.io/description: "Second workbench - will be QUEUED until GPU is released"
spec:
  template:
    spec:
      containers:
        - name: demo-workbench-2
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/pytorch:2025.1
          resources:
            limits:
              cpu: "4"
              memory: 16Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "2"
              memory: 8Gi
              nvidia.com/gpu: "1"
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          volumeMounts:
            - name: workbench-data
              mountPath: /opt/app-root/src
            - name: demo-notebooks
              mountPath: /opt/app-root/src/demo
              readOnly: true
          env:
            - name: NOTEBOOK_ARGS
              value: "--NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*'"
      # Target g6.4xlarge nodes (single L4 GPU)
      nodeSelector:
        node.kubernetes.io/instance-type: g6.4xlarge
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: workbench-data
          persistentVolumeClaim:
            claimName: demo-workbench-2-pvc
        - name: demo-notebooks
          configMap:
            name: gpu-demo-notebooks


