# Demo Workbench 1 - Gets the GPU first
# This workbench will be ADMITTED immediately if GPU is available
# RHOAI 3.0: Uses inject-auth for kube-rbac-proxy sidecar (not inject-oauth)
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: demo-workbench-1
  namespace: private-ai
  labels:
    app: demo-workbench-1
    opendatahub.io/dashboard: "true"
    opendatahub.io/odh-managed: "true"
    # RHOAI 3.0: Queue name must be 'default' to match global HardwareProfiles
    kueue.x-k8s.io/queue-name: "default"
  annotations:
    # RHOAI 3.0: Use inject-auth (NOT inject-oauth - deprecated!)
    notebooks.opendatahub.io/inject-auth: "true"
    opendatahub.io/username: "ai-developer"
    notebooks.opendatahub.io/last-image-selection: "pytorch:2025.2"
    opendatahub.io/image-display-name: "Jupyter | PyTorch | CUDA | Python 3.12"
    openshift.io/display-name: "Demo Workbench 1 (GPU)"
    openshift.io/description: "First workbench - should get GPU immediately"
spec:
  template:
    spec:
      containers:
        - name: demo-workbench-1
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/pytorch:2025.2
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "4"
              memory: 16Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "4"
              memory: 16Gi
              nvidia.com/gpu: "1"
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          env:
            # RHOAI 3.0: MUST set base_url for path-based routing via Gateway API
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/private-ai/demo-workbench-1
                --ServerApp.quit_button=False
            - name: JUPYTER_IMAGE
              value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/pytorch:2025.2
          # Probes must use the base_url path
          livenessProbe:
            httpGet:
              path: /notebook/private-ai/demo-workbench-1/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /notebook/private-ai/demo-workbench-1/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: workbench-data
              mountPath: /opt/app-root/src
            - name: demo-notebooks
              mountPath: /opt/app-root/src/demo
              readOnly: true
            - name: shm
              mountPath: /dev/shm
          workingDir: /opt/app-root/src
      enableServiceLinks: false
      volumes:
        - name: workbench-data
          persistentVolumeClaim:
            claimName: demo-workbench-1-pvc
        - name: demo-notebooks
          configMap:
            name: gpu-demo-notebooks
        - name: shm
          emptyDir:
            medium: Memory
