# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: litemaas
  labels:
    app: postgres
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  # Red Hat PostgreSQL uses POSTGRESQL_* prefix
  POSTGRESQL_USER: litemaas_admin
  # URL-safe password (no special chars that break postgresql:// URLs)
  POSTGRESQL_PASSWORD: LiteMaaS2024SecurePass
  POSTGRESQL_DATABASE: litemaas_db
---
# PostgreSQL Init ConfigMap (database schema)
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: litemaas
  labels:
    app: postgres
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  init.sql: |
    -- LiteMaaS Database Schema
    -- This script initializes the database with required tables
    
    -- Users table
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        external_id VARCHAR(255) UNIQUE NOT NULL,
        email VARCHAR(255),
        display_name VARCHAR(255),
        roles TEXT[] DEFAULT ARRAY['user'],
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Subscriptions table
    CREATE TABLE IF NOT EXISTS subscriptions (
        id SERIAL PRIMARY KEY,
        user_id INTEGER REFERENCES users(id),
        model_id VARCHAR(255) NOT NULL,
        status VARCHAR(50) DEFAULT 'active',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- API Keys table
    CREATE TABLE IF NOT EXISTS api_keys (
        id SERIAL PRIMARY KEY,
        user_id INTEGER REFERENCES users(id),
        key_hash VARCHAR(255) NOT NULL,
        key_prefix VARCHAR(20) NOT NULL,
        name VARCHAR(255),
        scopes TEXT[],
        is_active BOOLEAN DEFAULT true,
        last_used_at TIMESTAMP,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Usage tracking table
    CREATE TABLE IF NOT EXISTS usage_logs (
        id SERIAL PRIMARY KEY,
        api_key_id INTEGER REFERENCES api_keys(id),
        model_id VARCHAR(255),
        tokens_input INTEGER DEFAULT 0,
        tokens_output INTEGER DEFAULT 0,
        request_time_ms INTEGER,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Models table
    CREATE TABLE IF NOT EXISTS models (
        id SERIAL PRIMARY KEY,
        model_id VARCHAR(255) UNIQUE NOT NULL,
        display_name VARCHAR(255),
        provider VARCHAR(100),
        is_active BOOLEAN DEFAULT true,
        config JSONB,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Create indexes
    CREATE INDEX IF NOT EXISTS idx_users_external_id ON users(external_id);
    CREATE INDEX IF NOT EXISTS idx_api_keys_prefix ON api_keys(key_prefix);
    CREATE INDEX IF NOT EXISTS idx_usage_logs_created ON usage_logs(created_at);
    CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON subscriptions(user_id);
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: litemaas
  labels:
    app: postgres
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: postgres
  type: ClusterIP
---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: litemaas
  labels:
    app: postgres
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/part-of: litemaas
    spec:
      containers:
        - name: postgres
          image: registry.redhat.io/rhel9/postgresql-15:latest
          ports:
            - containerPort: 5432
              name: postgresql
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
            - name: init-scripts
              mountPath: /opt/app-root/src/postgresql-init
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRESQL_USER -d $POSTGRESQL_DATABASE
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRESQL_USER -d $POSTGRESQL_DATABASE
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: init-scripts
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3-csi
        resources:
          requests:
            storage: 5Gi


# Post-init fix for OpenShift OAuth compatibility
# OpenShift OAuth doesn't provide a standard OIDC 'sub' claim,
# so oauth_id may be NULL for OpenShift users
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-oauth-fix
  namespace: litemaas
  labels:
    app: postgres
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: fix-schema
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              until psql "$DATABASE_URL" -c '\q' 2>/dev/null; do
                echo "Waiting for database..."
                sleep 2
              done
              echo "Making oauth_id nullable for OpenShift OAuth compatibility..."
              psql "$DATABASE_URL" -c "ALTER TABLE users ALTER COLUMN oauth_id DROP NOT NULL;" 2>/dev/null || true
              echo "Done!"
          env:
            - name: DATABASE_URL
              value: postgresql://litemaas_admin:LiteMaaS2024SecurePass@postgres:5432/litemaas_db
---
# Model Registration Job - registers models in backend database
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-register-models
  namespace: litemaas
  labels:
    app: postgres
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: register-models
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              until psql "$DATABASE_URL" -c '\q' 2>/dev/null; do
                echo "Waiting for database..."
                sleep 2
              done
              echo "Registering models in backend database..."
              psql "$DATABASE_URL" -c "
              INSERT INTO models (id, name, provider, description, category, context_length, input_cost_per_token, output_cost_per_token, supports_function_calling, supports_streaming, availability, api_base) VALUES
              ('mistral-3-int4', 'Mistral-3 INT4', 'vLLM', 'Mistral-3 INT4 quantized model (1-GPU)', 'chat', 16384, 0, 0, false, true, 'available', 'http://mistral-3-int4-predictor.private-ai.svc.cluster.local:8080/v1'),
              ('granite-8b-agent', 'Granite-8B Agent', 'vLLM', 'Granite-3.1-8B Agent for tool calling', 'agent', 16384, 0, 0, true, true, 'available', 'http://granite-8b-agent-predictor.private-ai.svc.cluster.local:8080/v1'),
              ('mistral-3-bf16', 'Mistral-3 BF16', 'vLLM', 'Mistral-3 BF16 full precision (4-GPU)', 'chat', 32768, 0, 0, false, true, 'available', 'http://mistral-3-bf16-predictor.private-ai.svc.cluster.local:8080/v1'),
              ('devstral-2', 'Devstral-2', 'vLLM', 'Devstral-2 agentic coding assistant (4-GPU)', 'coding', 131072, 0, 0, true, true, 'available', 'http://devstral-2-predictor.private-ai.svc.cluster.local:8080/v1'),
              ('gpt-oss-20b', 'GPT-OSS-20B', 'vLLM', 'GPT-OSS-20B for complex reasoning (4-GPU)', 'reasoning', 32768, 0, 0, false, true, 'available', 'http://gpt-oss-20b-predictor.private-ai.svc.cluster.local:8080/v1')
              ON CONFLICT (id) DO NOTHING;
              "
              echo "Models registered!"
          env:
            - name: DATABASE_URL
              value: postgresql://litemaas_admin:LiteMaaS2024SecurePass@postgres:5432/litemaas_db
