# ═══════════════════════════════════════════════════════════════════════════════
# PostgreSQL for LiteMaaS
# ═══════════════════════════════════════════════════════════════════════════════
# Stores: subscriptions, API keys, usage data, audit logs
# ═══════════════════════════════════════════════════════════════════════════════
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: litemaas
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  # Demo credentials - change for any real deployment
  # Red Hat PostgreSQL container uses POSTGRESQL_* prefix
  POSTGRESQL_USER: litemaas
  POSTGRESQL_PASSWORD: litemaas-demo-2024
  POSTGRESQL_DATABASE: litemaas
  DATABASE_URL: postgresql://litemaas:litemaas-demo-2024@postgres:5432/litemaas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: litemaas
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: litemaas
  annotations:
    # Same wave as Deployment - PVC uses WaitForFirstConsumer, needs pod to bind
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: litemaas
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: litemaas
    spec:
      containers:
        - name: postgres
          image: registry.redhat.io/rhel9/postgresql-15:latest
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: postgres-credentials
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRESQL_USER -d $POSTGRESQL_DATABASE
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRESQL_USER -d $POSTGRESQL_DATABASE
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: litemaas
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app.kubernetes.io/name: postgres

