# GuideLLM Realistic Load Test - Mistral-3 INT4 (1-GPU)
# ============================================================================
# Simulates realistic user traffic using Poisson distribution.
#
# Model: mistral-3-int4
# GPUs: 1 x NVIDIA L4
# Precision: INT4 (quantized)
#
# Benchmark Strategy:
#   - Poisson profile: Random arrival times (realistic user behavior)
#   - Rate: 5 requests/second average
#   - Duration: 5 minutes (300 seconds)
#   - Validates model performance under real-world conditions
#
# Usage:
#   oc create -f mistral-3-int4.yaml
# ============================================================================
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: benchmark-mistral-3-int4-
  namespace: private-ai
  labels:
    app: guidellm-pipeline
    model: mistral-3-int4
    app.kubernetes.io/part-of: benchmarking
spec:
  pipelineRef:
    name: guidellm-benchmark
  
  params:
    - name: model-name
      value: "mistral-3-int4"
    # Poisson profile: Realistic user arrival patterns
    - name: profile
      value: "poisson"
    - name: rate
      value: "5"
    - name: max-seconds
      value: "300"
    - name: max-requests
      value: "500"
  
  workspaces:
    # Use emptyDir to avoid affinity-assistant (which may land on GPU nodes)
    # Results are printed to logs; use CronJob + PVC for persistent results
    - name: results
      emptyDir: {}
  
  # Use CPU-only LocalQueue (points to 'default' ClusterQueue with default-flavor)
  # This ensures pipeline pods are scheduled on non-GPU nodes
  taskRunSpecs:
    - pipelineTaskName: benchmark
      metadata:
        labels:
          kueue.x-k8s.io/queue-name: cpu-workloads

