# GuideLLM Scheduled Benchmark CronJob
# ============================================================================
# Runs automated benchmark sweeps on a schedule.
# Default: Daily at 2:00 AM UTC
#
# Uses the official GuideLLM container image from:
# https://github.com/vllm-project/guidellm/pkgs/container/guidellm
#
# Results are persisted to the guidellm-results PVC.
#
# To trigger manually:
#   oc create job --from=cronjob/guidellm-daily manual-benchmark -n private-ai
# ============================================================================
apiVersion: batch/v1
kind: CronJob
metadata:
  name: guidellm-daily
  namespace: private-ai
  labels:
    app: guidellm
    app.kubernetes.io/part-of: step-07-model-performance-metrics
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  # Run daily at 2:00 AM UTC
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 3600  # 1 hour max
      template:
        metadata:
          labels:
            app: guidellm
            job-type: scheduled
        spec:
          restartPolicy: Never
          # Ensure PVC is writable by any user (OpenShift assigns random UID)
          securityContext:
            fsGroup: 0
          # Note: This job needs network access to download HuggingFace datasets/tokenizers
          # If running in a restricted environment, consider pre-downloading data
          containers:
            - name: guidellm
              # Official GuideLLM container image
              # Ref: https://github.com/vllm-project/guidellm/pkgs/container/guidellm
              image: ghcr.io/vllm-project/guidellm:nightly
              env:
                # Set HOME to writable directory for cache
                - name: HOME
                  value: /tmp
                # Set HuggingFace cache directory
                - name: HF_HOME
                  value: /tmp/.cache/huggingface
                # Set output directory for GuideLLM
                - name: GUIDELLM_OUTPUT_DIR
                  value: /results
              command:
                - /bin/bash
                - -c
                - |
                  echo "GuideLLM version:"
                  guidellm --version || echo "Version check not supported"
                  
                  echo "Running benchmark sweep..."
                  /scripts/benchmark-sweep.sh
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
                  readOnly: true
                - name: results
                  mountPath: /results
                - name: cache
                  mountPath: /tmp/.cache
              resources:
                requests:
                  cpu: 500m
                  memory: 512Mi
                limits:
                  cpu: "2"
                  memory: 2Gi
          volumes:
            - name: scripts
              configMap:
                name: guidellm-scripts
                defaultMode: 0555  # Read + Execute for all
            - name: results
              persistentVolumeClaim:
                claimName: guidellm-results
            - name: cache
              emptyDir: {}

