# GuideLLM Job Dispatcher RBAC
# ============================================================================
# Allows the dispatcher CronJob to create parallel benchmark Jobs.
# ============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guidellm-dispatcher
  namespace: private-ai
  labels:
    app: guidellm
    app.kubernetes.io/part-of: step-07-model-performance-metrics
  annotations:
    argocd.argoproj.io/sync-wave: "8"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: guidellm-job-creator
  namespace: private-ai
  labels:
    app: guidellm
    app.kubernetes.io/part-of: step-07-model-performance-metrics
  annotations:
    argocd.argoproj.io/sync-wave: "8"
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guidellm-dispatcher
  namespace: private-ai
  labels:
    app: guidellm
    app.kubernetes.io/part-of: step-07-model-performance-metrics
  annotations:
    argocd.argoproj.io/sync-wave: "8"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: guidellm-job-creator
subjects:
  - kind: ServiceAccount
    name: guidellm-dispatcher
    namespace: private-ai

