# Gateway for llm-d Distributed Inference
#
# This Gateway configuration matches the Red Hat reference implementation:
# https://github.com/rh-aiservices-bu/rhaoi3-llm-d
#
# Design Decision:
#   We use the simpler HTTP-based Gateway from the reference repo rather than
#   HTTPS with TLS termination. This avoids the TLS re-encryption complexity
#   when the backend vLLM service also uses HTTPS.
#
# ⚠️ IMPORTANT (cluster safety):
#   Do NOT set the Gateway listener hostname to `*.apps.<cluster_domain>`.
#   That can create a wildcard `DNSRecord` and temporarily overwrite the cluster
#   `*.apps` DNS entry, breaking the OpenShift console and all Routes.
#   Keep the Gateway hostname unset (or use a single dedicated hostname).
#
# For production deployments requiring TLS, configure:
#   1. Edge termination at the OpenShift Router level
#   2. Or use service mesh for mTLS between gateway and backend
#
# Ref: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.0/html-single/deploying_models/index

# GatewayClass - use OpenShift's default controller
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: openshift-default
  labels:
    app.kubernetes.io/name: openshift-default
    app.kubernetes.io/component: gateway-class
    app.kubernetes.io/part-of: llm-serving
    demo.rhoai.io/step: "08"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  controllerName: openshift.io/gateway-controller/v1
---
# Gateway - HTTP-based for simplicity (matching reference repo)
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  # Name MUST be "openshift-ai-inference" - llm-d controller validates against this name
  name: openshift-ai-inference
  namespace: openshift-ingress
  labels:
    app.kubernetes.io/name: openshift-ai-inference
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: llm-serving
    demo.rhoai.io/step: "08"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    openshift.io/display-name: "llm-d Distributed Inference Gateway"
    openshift.io/description: "HTTP Gateway for llm-d, matching Red Hat reference implementation"
spec:
  gatewayClassName: openshift-default
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All  # Allow routes from any namespace (demo simplicity)
