apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-chatbot
  namespace: enterprise-rag
  labels:
    app: rag-chatbot
    app.kubernetes.io/part-of: rag
    app.kubernetes.io/component: chatbot-ui
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rag-chatbot-nemo-client
  namespace: enterprise-rag
  labels:
    app: rag-chatbot
    app.kubernetes.io/part-of: rag
    app.kubernetes.io/component: chatbot-ui
  annotations:
    argocd.argoproj.io/sync-wave: "5"
subjects:
  - kind: ServiceAccount
    name: rag-chatbot
    namespace: enterprise-rag
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
