# LocalQueue 'default' - REQUIRED for global Hardware Profiles
# ============================================================================
# RHOAI 3.0 Best Practice: Use standardized 'default' name in each namespace
# Global HardwareProfiles use scheduling.kueue.localQueueName: "default"
#
# This LocalQueue points to our custom ClusterQueue (rhoai-main-queue) which:
# - Has higher GPU quota (10 GPUs vs 5 in RHOAI default)
# - Uses custom ResourceFlavors with nodeLabels for proper node targeting
# - Uses ResourceFlavors with tolerations for GPU node scheduling
# ============================================================================
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: default
  namespace: private-ai
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    kueue.x-k8s.io/default-queue: "true"
spec:
  # Points to our custom GPU-as-a-Service ClusterQueue
  # ResourceFlavors (nvidia-l4-1gpu, nvidia-l4-4gpu) inject:
  # - nodeLabels → nodeSelector (for instance type targeting)
  # - tolerations (for GPU node scheduling)
  clusterQueue: rhoai-main-queue
