# LocalQueue 'default' - RHOAI 3.0 Controller-Managed
# ============================================================================
# IMPORTANT: In RHOAI 3.0, the LocalQueue named 'default' is AUTOMATICALLY
# created and managed by the RHOAI controller based on DSCInitialization
# and DataScienceCluster settings.
#
# Configuration Source:
#   DataScienceCluster.spec.components.kueue:
#     defaultClusterQueueName: default
#     defaultLocalQueueName: default
#     managementState: Unmanaged
#
# This means:
#   1. RHOAI creates a LocalQueue named 'default' in every DSProject namespace
#   2. The LocalQueue points to the 'default' ClusterQueue (RHOAI-managed)
#   3. Custom clusterQueue assignments are OVERWRITTEN by the controller
#
# Best Practice for RHOAI 3.0:
#   - Use the RHOAI-managed 'default' ClusterQueue
#   - Ensure HardwareProfiles use localQueueName: "default"
#   - InferenceServices use kueue.x-k8s.io/queue-name: "default"
#
# The 'default' ClusterQueue includes GPU ResourceFlavors with proper
# node targeting and tolerations for GPU scheduling.
# ============================================================================
#
# NOTE: This file is kept for documentation purposes but will be overwritten
# by the RHOAI controller. The actual LocalQueue configuration comes from
# the DataScienceCluster CR in redhat-ods-applications namespace.
#
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: default
  namespace: private-ai
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: Replace=true
    kueue.x-k8s.io/default-queue: "true"
spec:
  # RHOAI controller will override this to 'default'
  clusterQueue: default
  stopPolicy: None
