apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - approve-installplan.yaml
  - authorino-subscription.yaml
  - dns-subscription.yaml
  - limitador-subscription.yaml
  - subscription.yaml
