apiVersion: v1
kind: Service
metadata:
  name: trustyai-adapter
  namespace: private-ai
  labels:
    app.kubernetes.io/name: trustyai-adapter
    app.kubernetes.io/part-of: face-recognition
    app.kubernetes.io/component: monitoring
spec:
  selector:
    app: trustyai-adapter
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http
  type: ClusterIP
