# Required prerequisite for KServe model serving in RHOAI 3.3
# Even with RawDeployment mode, Knative infrastructure is needed for the serving platform
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ingress:
    istio:
      enabled: false
  high-availability:
    replicas: 2
  config:
    features:
      kubernetes.podspec-affinity: enabled
      kubernetes.podspec-nodeselector: enabled
      kubernetes.podspec-tolerations: enabled
