apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: rhoai3-demo
      demo.rhoai.io/stage: "240"

resources:
  - project/base
  - rhoai-dsc/base
  - maas-proxy/base
  - guardrails/base
  - observability/base
