apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen3-reranker
  namespace: enterprise-rag
  labels:
    app.kubernetes.io/part-of: rag
    app.kubernetes.io/name: qwen3-reranker
    app.kubernetes.io/component: reranker
    kueue.x-k8s.io/queue-name: lq-cpu-default
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    openshift.io/display-name: qwen3-reranker
    opendatahub.io/model-type: generative
    security.opendatahub.io/enable-auth: "false"
    serving.kserve.io/deploymentMode: Standard
    serving.kserve.io/stop: "false"
spec:
  predictor:
    automountServiceAccountToken: false
    minReplicas: 1
    maxReplicas: 1
    deploymentStrategy:
      type: RollingUpdate
    model:
      runtime: qwen3-reranker
      modelFormat:
        name: vLLM
      storageUri: oci://quay.io/asoliman/qwen3-reranker-0.6b-seq-cls-modelcar:latest
      args:
        - --runner=pooling
        - --convert=classify
        - --dtype=float32
        - --max-model-len=1024
        - --max-num-seqs=4
        - --max-num-batched-tokens=512
      env:
        - name: VLLM_CPU_KVCACHE_SPACE
          value: "2"
      resources:
        requests:
          cpu: "4"
          memory: 10Gi
        limits:
          cpu: "8"
          memory: 16Gi
