apiVersion: v1
kind: Secret
metadata:
  name: nemo-guardrails-api-token
  namespace: enterprise-rag
  labels:
    app.kubernetes.io/part-of: guardrails
    app.kubernetes.io/component: safety
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
stringData:
  token: fake
