apiVersion: v1
kind: ServiceAccount
metadata:
  name: nemo-guardrails-service-account
  namespace: enterprise-rag
  labels:
    app.kubernetes.io/part-of: guardrails
    app.kubernetes.io/component: safety
  annotations:
    argocd.argoproj.io/sync-wave: "3"
