apiVersion: v1
kind: Namespace
metadata:
  name: litemaas
  labels:
    app.kubernetes.io/part-of: litemaas
    kubernetes.io/metadata.name: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: "LiteMaaS - Model as a Service"
    openshift.io/description: "Experimental MaaS platform for LLM subscriptions and API management"

