apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-kueue-operator
  namespace: openshift-kueue-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  # Red Hat build of Kueue supports AllNamespaces install mode.
  upgradeStrategy: Default
