# =============================================================================
# Model Upload Job: Mistral Small 24B to MinIO
# =============================================================================
# Downloads Mistral-Small-24B-Instruct from HuggingFace and uploads to MinIO
# 
# This job runs in minio-storage namespace (NOT Kueue-managed) to avoid
# quota constraints. It's a utility job, not a GPU workload.
#
# Usage:
#   1. Create HF token secret: oc create secret generic hf-token -n minio-storage --from-literal=token=hf_xxx
#   2. Apply job: oc apply -f upload-mistral-job.yaml
#   3. Monitor: oc logs -f job/upload-mistral-to-minio -n minio-storage
# =============================================================================
apiVersion: batch/v1
kind: Job
metadata:
  name: upload-mistral-to-minio
  namespace: minio-storage  # Not Kueue-managed - avoids quota constraints
  annotations:
    argocd.argoproj.io/hook: Skip
    description: "Downloads Mistral-Small-24B and uploads to MinIO for S3 serving"
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: uploader
          image: python:3.11-slim
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          command:
            - /bin/bash
            - -c
            - |
              set -e
              export HOME=/tmp
              echo "╔══════════════════════════════════════════════════════════════╗"
              echo "║  Model Upload: Mistral Small 24B → MinIO                     ║"
              echo "║  Part of RHOAI 3.0 S3 Handshake Pattern                      ║"
              echo "╚══════════════════════════════════════════════════════════════╝"
              
              echo "=== Installing dependencies ==="
              pip install --user -q huggingface_hub boto3 tqdm
              export PATH="$HOME/.local/bin:$PATH"

              python3 << 'PYTHON_SCRIPT'
              import os
              import sys
              from huggingface_hub import snapshot_download
              import boto3
              from botocore.config import Config
              from pathlib import Path

              # Configuration
              BUCKET = "models"
              S3_ENDPOINT = os.environ['MINIO_ENDPOINT']
              HF_TOKEN = os.environ.get("HF_TOKEN")

              # Initialize S3 client
              s3 = boto3.client(
                  's3',
                  endpoint_url=S3_ENDPOINT,
                  aws_access_key_id=os.environ['MINIO_ACCESS_KEY'],
                  aws_secret_access_key=os.environ['MINIO_SECRET_KEY'],
                  config=Config(signature_version='s3v4')
              )

              # Ensure bucket exists
              try:
                  s3.head_bucket(Bucket=BUCKET)
                  print(f"✓ Bucket '{BUCKET}' exists")
              except:
                  s3.create_bucket(Bucket=BUCKET)
                  print(f"✓ Created bucket '{BUCKET}'")

              # Check if model already exists
              try:
                  resp = s3.list_objects_v2(Bucket=BUCKET, Prefix="mistral-small-24b/", MaxKeys=1)
                  if resp.get('KeyCount', 0) > 0:
                      print("✓ Model already exists in S3 - skipping download")
                      sys.exit(0)
              except Exception as e:
                  print(f"  Note: {e}")

              # Download from HuggingFace
              print("\nDownloading mistralai/Mistral-Small-24B-Instruct-2501...")
              print("  This may take 30-60 minutes for ~50GB models")
              
              local_path = "/tmp/model"
              try:
                  snapshot_download(
                      repo_id="mistralai/Mistral-Small-24B-Instruct-2501",
                      local_dir=local_path,
                      token=HF_TOKEN,
                      ignore_patterns=["*.md", "*.txt", "*.git*"]
                  )
              except Exception as e:
                  print(f"❌ Download failed: {e}")
                  print(f"  Ensure HF_TOKEN is set for gated models")
                  sys.exit(1)

              # Upload to MinIO
              print("\nUploading to MinIO...")
              file_count = 0
              for file_path in Path(local_path).rglob("*"):
                  if file_path.is_file():
                      key = "mistral-small-24b/" + str(file_path.relative_to(local_path))
                      print(f"  → {key}")
                      s3.upload_file(str(file_path), BUCKET, key)
                      file_count += 1

              print(f"\n{'='*60}")
              print(f"✓ Uploaded {file_count} files to s3://{BUCKET}/mistral-small-24b/")
              print("  Ready for deployment from GenAI Studio")
              print(f"{'='*60}")
              PYTHON_SCRIPT
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
                  optional: true
            # MinIO credentials (same as minio-credentials secret in this namespace)
            - name: MINIO_ACCESS_KEY
              value: "rhoai-access-key"
            - name: MINIO_SECRET_KEY
              value: "rhoai-secret-key-12345"
            - name: MINIO_ENDPOINT
              value: "http://minio:9000"
          resources:
            requests:
              cpu: "2"
              memory: 8Gi
            limits:
              cpu: "4"
              memory: 16Gi
