# =============================================================================
# Model Upload Job: Mistral Small 24B to MinIO
# =============================================================================
# Downloads Mistral-Small-24B-Instruct from HuggingFace and uploads to MinIO
# 
# Uses a PVC for model download to avoid ephemeral storage issues.
# Runs in minio-storage namespace (not Kueue-managed).
#
# Usage:
#   1. Create HF token: oc create secret generic hf-token -n minio-storage --from-literal=token=hf_xxx
#   2. Apply job: oc apply -f upload-mistral-job.yaml
#   3. Monitor: oc logs -f job/upload-mistral-to-minio -n minio-storage
# =============================================================================
---
# PVC for model download (survives pod restarts, avoids ephemeral storage issues)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-download-pvc
  namespace: minio-storage
  annotations:
    argocd.argoproj.io/hook: Skip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: upload-mistral-to-minio
  namespace: minio-storage
  annotations:
    argocd.argoproj.io/hook: Skip
    description: "Downloads Mistral-Small-24B and uploads to MinIO for S3 serving"
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-download-pvc
      containers:
        - name: uploader
          image: python:3.11-slim
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: model-storage
              mountPath: /models
          command:
            - /bin/bash
            - -c
            - |
              set -e
              export HOME=/tmp
              echo "╔══════════════════════════════════════════════════════════════╗"
              echo "║  Model Upload: Mistral Small 24B → MinIO                     ║"
              echo "║  Using PVC for reliable storage                              ║"
              echo "╚══════════════════════════════════════════════════════════════╝"
              
              echo "=== Installing dependencies ==="
              pip install --user -q huggingface_hub boto3 tqdm
              export PATH="$HOME/.local/bin:$PATH"

              python3 << 'PYTHON_SCRIPT'
              import os
              import sys
              from huggingface_hub import snapshot_download
              import boto3
              from botocore.config import Config
              from pathlib import Path

              # Configuration
              BUCKET = "models"
              S3_ENDPOINT = os.environ['MINIO_ENDPOINT']
              HF_TOKEN = os.environ.get("HF_TOKEN")
              MODEL_DIR = "/models/mistral-small-24b"

              # Initialize S3 client
              s3 = boto3.client(
                  's3',
                  endpoint_url=S3_ENDPOINT,
                  aws_access_key_id=os.environ['MINIO_ACCESS_KEY'],
                  aws_secret_access_key=os.environ['MINIO_SECRET_KEY'],
                  config=Config(signature_version='s3v4')
              )

              # Ensure bucket exists
              try:
                  s3.head_bucket(Bucket=BUCKET)
                  print(f"✓ Bucket '{BUCKET}' exists")
              except:
                  s3.create_bucket(Bucket=BUCKET)
                  print(f"✓ Created bucket '{BUCKET}'")

              # Check if model already exists in MinIO
              try:
                  resp = s3.list_objects_v2(Bucket=BUCKET, Prefix="mistral-small-24b/", MaxKeys=1)
                  if resp.get('KeyCount', 0) > 0:
                      print("✓ Model already exists in MinIO - skipping")
                      sys.exit(0)
              except Exception as e:
                  print(f"  Note: {e}")

              # Check if model already downloaded to PVC
              model_path = Path(MODEL_DIR)
              if model_path.exists() and any(model_path.iterdir()):
                  print(f"✓ Model found on PVC at {MODEL_DIR}")
              else:
                  # Download from HuggingFace to PVC
                  print("\nDownloading mistralai/Mistral-Small-24B-Instruct-2501 to PVC...")
                  print("  This may take 30-60 minutes for ~50GB models")
                  
                  try:
                      snapshot_download(
                          repo_id="mistralai/Mistral-Small-24B-Instruct-2501",
                          local_dir=MODEL_DIR,
                          token=HF_TOKEN,
                          ignore_patterns=["*.md", "*.txt", "*.git*"]
                      )
                  except Exception as e:
                      print(f"❌ Download failed: {e}")
                      print(f"  Ensure HF_TOKEN is set for gated models")
                      sys.exit(1)

              # Upload from PVC to MinIO
              print("\nUploading to MinIO...")
              file_count = 0
              for file_path in Path(MODEL_DIR).rglob("*"):
                  if file_path.is_file():
                      key = "mistral-small-24b/" + str(file_path.relative_to(MODEL_DIR))
                      print(f"  → {key}")
                      s3.upload_file(str(file_path), BUCKET, key)
                      file_count += 1

              print(f"\n{'='*60}")
              print(f"✓ Uploaded {file_count} files to s3://{BUCKET}/mistral-small-24b/")
              print("  Ready for deployment from GenAI Studio")
              print(f"{'='*60}")
              PYTHON_SCRIPT
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
                  optional: true
            - name: MINIO_ACCESS_KEY
              value: "rhoai-access-key"
            - name: MINIO_SECRET_KEY
              value: "rhoai-secret-key-12345"
            - name: MINIO_ENDPOINT
              value: "http://minio:9000"
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 8Gi
