# Ref: https://github.com/redhat-cop/gitops-catalog/tree/main/grafana-operator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml

