# Model Registration Job - Enterprise Governance
# Pre-populates the Model Registry with the May 2025 Validated Granite model
#
# This implements the "Gatekeeper" pattern:
# - Only ai-admin can register models (governance)
# - Models are vetted and validated before appearing in the catalog
# - Developers discover models via GenAI Studio, not Hugging Face
#
# IMPORTANT: This job ONLY registers metadata. It does NOT deploy the model.
apiVersion: batch/v1
kind: Job
metadata:
  name: model-registry-seed
  namespace: rhoai-model-registries
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: model-registry-seed
    spec:
      restartPolicy: OnFailure
      # OpenShift 4.20 restricted-v2 SCC compliance
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: seed
          image: registry.redhat.io/ubi9/python-311:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          command:
            - /bin/bash
            - -ce
            - |
              # ═══════════════════════════════════════════════════════════════════
              # Wait for Model Registry REST API to be ready
              # ═══════════════════════════════════════════════════════════════════
              REGISTRY_URL="http://private-ai-registry.rhoai-model-registries.svc:8080"
              
              echo "╔══════════════════════════════════════════════════════════════╗"
              echo "║  Enterprise Model Governance - Model Registration            ║"
              echo "║  May 2025 Red Hat Validated Collection                       ║"
              echo "╚══════════════════════════════════════════════════════════════╝"
              echo ""
              echo "Waiting for Model Registry at ${REGISTRY_URL}..."
              
              TIMEOUT=300
              ELAPSED=0
              until curl -sf "${REGISTRY_URL}/api/model_registry/v1alpha3/registered_models" > /dev/null 2>&1; do
                if [ $ELAPSED -ge $TIMEOUT ]; then
                  echo "ERROR: Timeout waiting for Model Registry"
                  exit 1
                fi
                echo "Model Registry is unavailable - sleeping 10s... (${ELAPSED}s/${TIMEOUT}s)"
                sleep 10
                ELAPSED=$((ELAPSED + 10))
              done
              echo "✓ Model Registry is ready!"
              echo ""
              
              # ═══════════════════════════════════════════════════════════════════
              # Register: Granite-3.1-8b-Instruct-FP8
              # Red Hat AI Validated Model - May 2025 Collection
              # https://huggingface.co/RedHatAI/granite-3.1-8b-instruct-FP8-dynamic
              # ═══════════════════════════════════════════════════════════════════
              MODEL_NAME="Granite-3.1-8b-Instruct-FP8"
              
              echo "Registering model: ${MODEL_NAME}..."
              
              # Check if model already exists
              EXISTING=$(curl -sf "${REGISTRY_URL}/api/model_registry/v1alpha3/registered_models?name=${MODEL_NAME}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(len(d.get('items', [])))" 2>/dev/null || echo "0")
              
              if [ "$EXISTING" != "0" ]; then
                echo "✓ Model already registered - skipping"
                exit 0
              fi
              
              # ─────────────────────────────────────────────────────────────────
              # Step 1: Create RegisteredModel (the "product" entry)
              # ─────────────────────────────────────────────────────────────────
              echo "Creating RegisteredModel..."
              
              REGISTERED_MODEL=$(curl -sf -X POST "${REGISTRY_URL}/api/model_registry/v1alpha3/registered_models" \
                -H "Content-Type: application/json" \
                -d '{
                  "name": "Granite-3.1-8b-Instruct-FP8",
                  "description": "IBM Granite 3.1 8B Instruct model with FP8 dynamic quantization. Part of the Red Hat AI Validated Models collection (May 2025). Optimized for NVIDIA L4 GPUs.",
                  "owner": "ai-admin",
                  "customProperties": {
                    "vendor": {"stringValue": "IBM"},
                    "collection": {"stringValue": "Red Hat AI Validated - May 2025"},
                    "validated_by": {"stringValue": "Red Hat AI"},
                    "license": {"stringValue": "Apache-2.0"},
                    "task": {"stringValue": "text-generation"},
                    "base_model": {"stringValue": "ibm-granite/granite-3.1-8b-instruct"},
                    "quantization": {"stringValue": "FP8-dynamic"},
                    "hardware_target": {"stringValue": "NVIDIA L4 (AWS G6)"}
                  }
                }')
              
              MODEL_ID=$(echo "$REGISTERED_MODEL" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id', ''))")
              
              if [ -z "$MODEL_ID" ]; then
                echo "ERROR: Failed to create RegisteredModel"
                echo "Response: $REGISTERED_MODEL"
                exit 1
              fi
              echo "✓ Created RegisteredModel with ID: $MODEL_ID"
              
              # ─────────────────────────────────────────────────────────────────
              # Step 2: Create ModelVersion (the specific release)
              # ─────────────────────────────────────────────────────────────────
              echo "Creating ModelVersion: 3.1-May2025-Validated..."
              
              MODEL_VERSION=$(curl -sf -X POST "${REGISTRY_URL}/api/model_registry/v1alpha3/model_versions" \
                -H "Content-Type: application/json" \
                -d "{
                  \"name\": \"3.1-May2025-Validated\",
                  \"registeredModelId\": \"$MODEL_ID\",
                  \"description\": \"Red Hat Validated release for May 2025. Tested on OpenShift AI 3.0 with vLLM on NVIDIA L4 GPUs.\",
                  \"author\": \"ai-admin\",
                  \"customProperties\": {
                    \"validation_date\": {\"stringValue\": \"2025-05\"},
                    \"rhoai_version\": {\"stringValue\": \"3.0\"},
                    \"serving_runtime\": {\"stringValue\": \"vLLM\"},
                    \"gpu_required\": {\"stringValue\": \"1\"},
                    \"min_gpu_memory\": {\"stringValue\": \"16Gi\"},
                    \"status\": {\"stringValue\": \"Ready to Deploy\"}
                  }
                }")
              
              VERSION_ID=$(echo "$MODEL_VERSION" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id', ''))")
              
              if [ -z "$VERSION_ID" ]; then
                echo "ERROR: Failed to create ModelVersion"
                echo "Response: $MODEL_VERSION"
                exit 1
              fi
              echo "✓ Created ModelVersion with ID: $VERSION_ID"
              
              # ─────────────────────────────────────────────────────────────────
              # Step 3: Create ModelArtifact (S3 reference to model weights)
              # ─────────────────────────────────────────────────────────────────
              echo "Creating ModelArtifact (S3 reference)..."
              
              ARTIFACT=$(curl -sf -X POST "${REGISTRY_URL}/api/model_registry/v1alpha3/model_artifacts" \
                -H "Content-Type: application/json" \
                -d "{
                  \"name\": \"granite-3.1-8b-instruct-fp8-weights\",
                  \"modelVersionId\": \"$VERSION_ID\",
                  \"description\": \"Model weights in safetensors format with FP8 dynamic quantization\",
                  \"uri\": \"s3://models/granite-3.1-8b-instruct-FP8-dynamic/\",
                  \"artifactType\": \"model-artifact\",
                  \"customProperties\": {
                    \"s3_endpoint\": {\"stringValue\": \"http://minio.minio-storage.svc:9000\"},
                    \"s3_bucket\": {\"stringValue\": \"models\"},
                    \"format\": {\"stringValue\": \"safetensors\"},
                    \"size_gb\": {\"stringValue\": \"8.5\"},
                    \"huggingface_repo\": {\"stringValue\": \"RedHatAI/granite-3.1-8b-instruct-FP8-dynamic\"}
                  }
                }")
              
              ARTIFACT_ID=$(echo "$ARTIFACT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id', ''))")
              
              if [ -z "$ARTIFACT_ID" ]; then
                echo "ERROR: Failed to create ModelArtifact"
                echo "Response: $ARTIFACT"
                exit 1
              fi
              echo "✓ Created ModelArtifact with ID: $ARTIFACT_ID"
              
              # ─────────────────────────────────────────────────────────────────
              # Summary
              # ─────────────────────────────────────────────────────────────────
              echo ""
              echo "╔══════════════════════════════════════════════════════════════╗"
              echo "║  Model Registration Complete                                 ║"
              echo "╚══════════════════════════════════════════════════════════════╝"
              echo ""
              echo "  Model:        Granite-3.1-8b-Instruct-FP8"
              echo "  Version:      3.1-May2025-Validated"
              echo "  Status:       Ready to Deploy"
              echo "  Collection:   Red Hat AI Validated - May 2025"
              echo ""
              echo "  Artifact URI: s3://models/granite-3.1-8b-instruct-FP8-dynamic/"
              echo "  Hardware:     NVIDIA L4 (AWS G6) - FP8 optimized"
              echo ""
              echo "┌──────────────────────────────────────────────────────────────┐"
              echo "│  Next Steps:                                                 │"
              echo "│  1. View in Dashboard: GenAI Studio → AI Available Assets   │"
              echo "│  2. Deploy in Step 05: Click 'Deploy' → Select Hardware     │"
              echo "│  3. Use in Agents: Step 06 will connect to this endpoint    │"
              echo "└──────────────────────────────────────────────────────────────┘"
