apiVersion: batch/v1
kind: Job
metadata:
  name: model-registry-seed
  namespace: rhoai-model-registries
  labels:
    app: model-registry-seed
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    description: |
      Seeds the Model Registry with the May 2025 Red Hat Validated Granite model.
      Uses the internal service (port 8080) for cluster-internal API access.
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: model-registry-seed
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: seed
          image: quay.io/curl/curl:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
            # Uses internal service (port 8080) - bypasses OAuth proxy
            # The primary service (8443) remains protected for Dashboard/UI access
            - name: REGISTRY_URL
              value: "http://private-ai-registry-internal.rhoai-model-registries.svc:8080"
            - name: MODEL_NAME
              value: "Granite-3.1-8b-Instruct-FP8"
            - name: MODEL_VERSION
              value: "3.1-May2025-Validated"
            - name: MODEL_URI
              value: "s3://rhoai-artifacts/granite-3.1-8b-instruct-FP8-dynamic/"
            - name: MODEL_DESCRIPTION
              value: "IBM Granite 3.1 8B Instruct - Red Hat AI Validated (May 2025) - FP8 Dynamic Quantization"
          command:
            - /bin/sh
            - -ce
            - |
              echo "╔══════════════════════════════════════════════════════════════╗"
              echo "║  Enterprise Model Governance - Model Registration            ║"
              echo "║  May 2025 Red Hat Validated Collection                       ║"
              echo "╚══════════════════════════════════════════════════════════════╝"
              
              API_BASE="${REGISTRY_URL}/api/model_registry/v1alpha3"
              
              echo "Waiting for Model Registry API at ${REGISTRY_URL}..."
              
              # Wait for API to be ready
              for i in $(seq 1 30); do
                if curl -sf "${API_BASE}/registered_models" > /dev/null 2>&1; then
                  echo "✓ Model Registry API is ready!"
                  break
                fi
                echo "  Attempt $i/30 - waiting..."
                sleep 10
              done
              
              # Check if model already exists
              echo ""
              echo "Checking for existing model: ${MODEL_NAME}..."
              EXISTING=$(curl -sf "${API_BASE}/registered_models" | grep -c "${MODEL_NAME}" || true)
              
              if [ "$EXISTING" -gt 0 ]; then
                echo "✓ Model '${MODEL_NAME}' already registered - skipping"
                echo ""
                echo "Current registered models:"
                curl -sf "${API_BASE}/registered_models" | head -100
                exit 0
              fi
              
              echo ""
              echo "Registering model: ${MODEL_NAME}..."
              
              # Step 1: Create RegisteredModel
              echo "  [1/3] Creating RegisteredModel..."
              REGISTERED_MODEL=$(curl -sf -X POST "${API_BASE}/registered_models" \
                -H "Content-Type: application/json" \
                -d "{
                  \"name\": \"${MODEL_NAME}\",
                  \"description\": \"${MODEL_DESCRIPTION}\",
                  \"customProperties\": {
                    \"validated_by\": {\"stringValue\": \"Red Hat AI\"},
                    \"collection\": {\"stringValue\": \"May-2025-Validated\"},
                    \"quantization\": {\"stringValue\": \"FP8-dynamic\"}
                  }
                }")
              
              REGISTERED_MODEL_ID=$(echo "$REGISTERED_MODEL" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)
              echo "  ✓ Created RegisteredModel ID: ${REGISTERED_MODEL_ID}"
              
              # Step 2: Create ModelVersion
              echo "  [2/3] Creating ModelVersion..."
              MODEL_VERSION_RESP=$(curl -sf -X POST "${API_BASE}/model_versions" \
                -H "Content-Type: application/json" \
                -d "{
                  \"name\": \"${MODEL_VERSION}\",
                  \"description\": \"Production-ready version validated for NVIDIA L4 GPUs\",
                  \"registeredModelId\": \"${REGISTERED_MODEL_ID}\",
                  \"customProperties\": {
                    \"hardware_target\": {\"stringValue\": \"nvidia-l4\"},
                    \"validation_date\": {\"stringValue\": \"2025-05\"}
                  }
                }")
              
              MODEL_VERSION_ID=$(echo "$MODEL_VERSION_RESP" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)
              echo "  ✓ Created ModelVersion ID: ${MODEL_VERSION_ID}"
              
              # Step 3: Create ModelArtifact
              echo "  [3/3] Creating ModelArtifact..."
              ARTIFACT_RESP=$(curl -sf -X POST "${API_BASE}/model_versions/${MODEL_VERSION_ID}/artifacts" \
                -H "Content-Type: application/json" \
                -d "{
                  \"name\": \"${MODEL_NAME}-weights\",
                  \"uri\": \"${MODEL_URI}\",
                  \"artifactType\": \"model-artifact\",
                  \"modelFormatName\": \"safetensors\",
                  \"modelFormatVersion\": \"1.0\",
                  \"customProperties\": {
                    \"storage_type\": {\"stringValue\": \"s3\"},
                    \"bucket\": {\"stringValue\": \"rhoai-artifacts\"}
                  }
                }")
              
              ARTIFACT_ID=$(echo "$ARTIFACT_RESP" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)
              echo "  ✓ Created ModelArtifact ID: ${ARTIFACT_ID}"
              
              echo ""
              echo "════════════════════════════════════════════════════════════════"
              echo "✓ SUCCESS: Model registered in Model Registry"
              echo ""
              echo "  Model:    ${MODEL_NAME}"
              echo "  Version:  ${MODEL_VERSION}"
              echo "  Artifact: ${MODEL_URI}"
              echo ""
              echo "  The model is now visible in:"
              echo "  → GenAI Studio → AI Available Assets"
              echo "════════════════════════════════════════════════════════════════"

