apiVersion: batch/v1
kind: Job
metadata:
  name: model-registry-seed
  namespace: rhoai-model-registries
  labels:
    app: model-registry-seed
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    description: |
      Seeds the Model Registry with the May 2025 Red Hat Validated Granite model.
      Uses the internal service (port 8080) for cluster-internal API access.
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: model-registry-seed
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: seed
          image: quay.io/curl/curl:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
            # Uses internal service (port 8080) - bypasses OAuth proxy
            # The primary service (8443) remains protected for Dashboard/UI access
            - name: REGISTRY_URL
              value: "http://private-ai-registry-internal.rhoai-model-registries.svc:8080"
            - name: MODEL_NAME
              value: "Granite-3.1-8b-Instruct-FP8"
            - name: MODEL_VERSION
              value: "3.1-May2025-Validated"
            - name: MODEL_URI
              value: "s3://rhoai-artifacts/granite-3.1-8b-instruct-FP8-dynamic/"
            - name: MODEL_DESCRIPTION
              value: "IBM Granite 3.1 8B Instruct - Red Hat AI Validated (May 2025) - FP8 Dynamic Quantization"
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "╔══════════════════════════════════════════════════════════════╗"
              echo "║  Enterprise Model Governance - Model Registration            ║"
              echo "║  May 2025 Red Hat Validated Collection                       ║"
              echo "╚══════════════════════════════════════════════════════════════╝"
              
              API_BASE="${REGISTRY_URL}/api/model_registry/v1alpha3"
              
              echo "Waiting for Model Registry API at ${REGISTRY_URL}..."
              
              # Wait for API to be ready
              for i in $(seq 1 30); do
                if curl -sf "${API_BASE}/registered_models" > /dev/null 2>&1; then
                  echo "✓ Model Registry API is ready!"
                  break
                fi
                echo "  Attempt $i/30 - waiting..."
                sleep 10
              done
              
              # Check if model already exists (any state - archived or live)
              # The registry doesn't allow duplicate names, so we check and exit early
              echo ""
              echo "Checking for existing model: ${MODEL_NAME}..."
              MODELS_JSON=$(curl -sf "${API_BASE}/registered_models" 2>/dev/null || echo "{}")
              
              if echo "$MODELS_JSON" | grep -q "\"name\":\"${MODEL_NAME}\""; then
                echo "✓ Model '${MODEL_NAME}' already exists in registry"
                echo ""
                echo "  Note: To update metadata, use the Dashboard or PATCH API"
                echo ""
                echo "Current registered models:"
                echo "$MODELS_JSON" | grep -E '"name"|"state"|"owner"' | head -20
                exit 0
              fi
              
              echo "  Model not found - proceeding with registration"
              
              echo ""
              echo "Registering model: ${MODEL_NAME}..."
              
              # Step 1: Create RegisteredModel with proper metadata format
              # Using the same format as RHOAI Dashboard catalog registration
              echo "  [1/3] Creating RegisteredModel..."
              REGISTERED_MODEL=$(curl -sf -X POST "${API_BASE}/registered_models" \
                -H "Content-Type: application/json" \
                -d '{
                  "name": "'"${MODEL_NAME}"'",
                  "description": "'"${MODEL_DESCRIPTION}"'",
                  "owner": "ai-admin",
                  "customProperties": {
                    "granite": {"metadataType": "MetadataStringValue", "string_value": ""},
                    "fp8": {"metadataType": "MetadataStringValue", "string_value": ""},
                    "validated": {"metadataType": "MetadataStringValue", "string_value": ""},
                    "vllm": {"metadataType": "MetadataStringValue", "string_value": ""},
                    "text-to-text": {"metadataType": "MetadataStringValue", "string_value": ""},
                    "conversational": {"metadataType": "MetadataStringValue", "string_value": ""},
                    "compressed-tensors": {"metadataType": "MetadataStringValue", "string_value": ""}
                  }
                }' 2>&1)
              
              echo "  Response: $REGISTERED_MODEL"
              REGISTERED_MODEL_ID=$(echo "$REGISTERED_MODEL" | sed 's/.*"id":"\([^"]*\)".*/\1/' | head -1)
              echo "  ✓ Created RegisteredModel ID: ${REGISTERED_MODEL_ID}"
              
              # Step 2: Create ModelVersion with license and provider metadata
              echo "  [2/3] Creating ModelVersion..."
              MODEL_VERSION_RESP=$(curl -sf -X POST "${API_BASE}/model_versions" \
                -H "Content-Type: application/json" \
                -d '{
                  "name": "'"${MODEL_VERSION}"'",
                  "description": "Production-ready version validated for NVIDIA L4 GPUs",
                  "author": "ai-admin",
                  "registeredModelId": "'"${REGISTERED_MODEL_ID}"'",
                  "customProperties": {
                    "License": {"metadataType": "MetadataStringValue", "string_value": "https://www.apache.org/licenses/LICENSE-2.0"},
                    "Provider": {"metadataType": "MetadataStringValue", "string_value": "IBM"},
                    "validated_on": {"metadataType": "MetadataStringValue", "string_value": "RHOAI 3.0"},
                    "granite": {"metadataType": "MetadataStringValue", "string_value": ""},
                    "fp8": {"metadataType": "MetadataStringValue", "string_value": ""},
                    "validated": {"metadataType": "MetadataStringValue", "string_value": ""},
                    "vllm": {"metadataType": "MetadataStringValue", "string_value": ""}
                  }
                }' 2>&1)
              
              echo "  Response: $MODEL_VERSION_RESP"
              MODEL_VERSION_ID=$(echo "$MODEL_VERSION_RESP" | sed 's/.*"id":"\([^"]*\)".*/\1/' | head -1)
              echo "  ✓ Created ModelVersion ID: ${MODEL_VERSION_ID}"
              
              # Step 3: Create ModelArtifact with source tracking
              echo "  [3/3] Creating ModelArtifact..."
              ARTIFACT_RESP=$(curl -sf -X POST "${API_BASE}/model_versions/${MODEL_VERSION_ID}/artifacts" \
                -H "Content-Type: application/json" \
                -d '{
                  "name": "'"${MODEL_VERSION}"'",
                  "description": "FP8 dynamic quantized model weights",
                  "uri": "'"${MODEL_URI}"'",
                  "artifactType": "model-artifact",
                  "modelSourceClass": "redhat_ai_validated_models",
                  "modelSourceKind": "catalog",
                  "modelSourceName": "RedHatAI/granite-3.1-8b-instruct-FP8-dynamic"
                }' 2>&1)
              
              echo "  Response: $ARTIFACT_RESP"
              ARTIFACT_ID=$(echo "$ARTIFACT_RESP" | sed 's/.*"id":"\([^"]*\)".*/\1/' | head -1)
              echo "  ✓ Created ModelArtifact ID: ${ARTIFACT_ID}"
              
              echo ""
              echo "════════════════════════════════════════════════════════════════"
              echo "✓ SUCCESS: Model registered in Model Registry"
              echo ""
              echo "  Model:    ${MODEL_NAME}"
              echo "  Version:  ${MODEL_VERSION}"
              echo "  Artifact: ${MODEL_URI}"
              echo "  Owner:    ai-admin"
              echo ""
              echo "  Metadata Tags: granite, fp8, validated, vllm"
              echo "  License: Apache 2.0 | Provider: IBM"
              echo ""
              echo "  The model is now visible in:"
              echo "  → GenAI Studio → AI Available Assets"
              echo "════════════════════════════════════════════════════════════════"

