apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
  labels:
    app.kubernetes.io/name: alertmanager-main
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/part-of: rhoai3-demo
    demo.rhoai.io/stage: "210"
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      http_config:
        proxy_from_environment: true
    inhibit_rules:
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = critical
        target_matchers:
          - severity =~ warning|info
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = warning
        target_matchers:
          - severity = info
    route:
      group_by:
        - namespace
      group_interval: 5m
      group_wait: 30s
      receiver: Default
      repeat_interval: 12h
      routes:
        - matchers:
            - alertname = Watchdog
          receiver: Watchdog
          repeat_interval: 5m
        - matchers:
            - severity = critical
          receiver: Critical
    receivers:
      - name: Default
        webhook_configs:
          - send_resolved: true
            url: http://rhoai-demo-alert-webhook.openshift-monitoring.svc:8080/default
      - name: Watchdog
        webhook_configs:
          - send_resolved: false
            url: http://rhoai-demo-alert-webhook.openshift-monitoring.svc:8080/watchdog
      - name: Critical
        webhook_configs:
          - send_resolved: true
            url: http://rhoai-demo-alert-webhook.openshift-monitoring.svc:8080/critical
