apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/name: openshift-user-workload-monitoring
    app.kubernetes.io/component: monitoring
data:
  config.yaml: |
    enableUserWorkload: true
