apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alert-webhook-deployment.yaml
  - alert-webhook-service.yaml
  - alertmanager-main-secret.yaml
  - cluster-monitoring-config.yaml
  - user-workload-monitoring-config.yaml
