apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-operator
  labels:
    app.kubernetes.io/name: openshift-cert-manager-operator
    app.kubernetes.io/component: certificate-management
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    openshift.io/display-name: cert-manager Operator
