apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cert-manager-operator-og
  namespace: cert-manager-operator
  labels:
    app.kubernetes.io/name: openshift-cert-manager-operator
    app.kubernetes.io/component: certificate-management
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - cert-manager-operator
  upgradeStrategy: Default
