apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llamastack-postgres-anyuid
  namespace: private-ai
  labels:
    app: llamastack-postgres
    app.kubernetes.io/part-of: rag
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: llamastack-postgres
    namespace: private-ai
