# GuideLLM Benchmark Pipeline
# ============================================================================
# Tekton Pipeline for running GuideLLM benchmarks.
#
# Provides self-service benchmark execution with:
#   - Configurable model selection
#   - Benchmark profile options
#   - Persistent results storage
#   - Status reporting
#
# Use the pre-configured PipelineRuns in pipelineruns/ for each model.
#
# Ref: https://github.com/rh-aiservices-bu/guidellm-pipeline
# ============================================================================
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: guidellm-benchmark
  namespace: private-ai
  labels:
    app: guidellm-pipeline
    app.kubernetes.io/part-of: benchmarking
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  description: |
    GuideLLM Benchmark Pipeline for evaluating LLM inference performance.
    
    Measures key metrics:
    - Time To First Token (TTFT)
    - Token Output Rate (TPOT)
    - Request Throughput
    - Latency distributions
    
    Results are stored in the guidellm-pipeline-results PVC.
  
  params:
    - name: model-name
      type: string
      description: Name of the model to benchmark
    
    - name: target-url
      type: string
      description: Model endpoint URL (leave empty for auto-discovery)
      default: ""
    
    - name: profile
      type: string
      description: |
        Benchmark profile to use:
        - sweep: Runs multiple rate profiles (synchronous, throughput, constant rates)
        - throughput: Maximum throughput test
        - synchronous: One request at a time
      default: "sweep"
    
    - name: max-seconds
      type: string
      description: Maximum seconds per benchmark strategy
      default: "60"
    
    - name: max-requests
      type: string
      description: Maximum requests per benchmark strategy
      default: "50"
  
  workspaces:
    - name: results
      description: Workspace for storing benchmark results
  
  results:
    - name: output-file
      description: Path to the benchmark results
      value: $(tasks.benchmark.results.output-file)
    - name: status
      description: Benchmark status
      value: $(tasks.benchmark.results.status)
  
  tasks:
    - name: benchmark
      taskRef:
        name: guidellm-benchmark
      params:
        - name: model-name
          value: $(params.model-name)
        - name: target-url
          value: $(params.target-url)
        - name: profile
          value: $(params.profile)
        - name: max-seconds
          value: $(params.max-seconds)
        - name: max-requests
          value: $(params.max-requests)
      workspaces:
        - name: results
          workspace: results

