# GuideLLM Realistic Load Test Pipeline
# ============================================================================
# Tekton Pipeline for realistic user load testing using GuideLLM.
#
# Default Configuration:
#   - Poisson profile: Simulates real user arrival patterns
#   - 5 requests/second average rate
#   - 5 minutes duration for statistical significance
#
# Use the pre-configured PipelineRuns in pipelineruns/ for each model.
#
# Ref: https://github.com/rh-aiservices-bu/guidellm-pipeline
# ============================================================================
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: guidellm-benchmark
  namespace: private-ai
  labels:
    app: guidellm-pipeline
    app.kubernetes.io/part-of: benchmarking
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  description: |
    GuideLLM Benchmark Pipeline for evaluating LLM inference performance.
    
    Measures key metrics:
    - Time To First Token (TTFT)
    - Token Output Rate (TPOT)
    - Request Throughput
    - Latency distributions
    
    Results are stored in the guidellm-pipeline-results PVC.
  
  params:
    - name: model-name
      type: string
      description: Name of the model to benchmark
    
    - name: target-url
      type: string
      description: Model endpoint URL (leave empty for auto-discovery)
      default: ""
    
    - name: profile
      type: string
      description: |
        Benchmark profile:
        - poisson: Realistic user load (Poisson-distributed arrivals) [default]
        - constant: Fixed request rate (for breaking point analysis)
        - sweep: Multiple strategies (sync, throughput, constant 1-8)
        - synchronous: One request at a time
        - throughput: Maximum throughput test
      default: "poisson"
    
    - name: rate
      type: string
      description: Request rate (requests/second)
      default: "5"
    
    - name: max-seconds
      type: string
      description: Maximum seconds per benchmark strategy
      default: "300"
    
    - name: max-requests
      type: string
      description: Maximum requests per benchmark strategy
      default: "500"
  
  workspaces:
    - name: results
      description: Workspace for storing benchmark results
  
  results:
    - name: output-file
      description: Path to the benchmark results
      value: $(tasks.benchmark.results.output-file)
    - name: status
      description: Benchmark status
      value: $(tasks.benchmark.results.status)
  
  tasks:
    - name: benchmark
      taskRef:
        name: guidellm-benchmark
      params:
        - name: model-name
          value: $(params.model-name)
        - name: target-url
          value: $(params.target-url)
        - name: profile
          value: $(params.profile)
        - name: rate
          value: $(params.rate)
        - name: max-seconds
          value: $(params.max-seconds)
        - name: max-requests
          value: $(params.max-requests)
      workspaces:
        - name: results
          workspace: results

