apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: maas-gateway
  namespace: openshift-ingress
  labels:
    app.kubernetes.io/name: maas-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: models-as-a-service
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    openshift.io/description: External route for the RHOAI 3.4 Models-as-a-Service Gateway API gateway.
spec:
  to:
    kind: Service
    name: maas-default-gateway-data-science-gateway-class
    weight: 100
  port:
    targetPort: 443
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
