apiVersion: v1
kind: Service
metadata:
  name: maas-postgres
  namespace: redhat-ods-applications
  labels:
    app: maas-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  selector:
    app: maas-postgres
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  type: ClusterIP
