# KEDA Authentication for Thanos/Prometheus Metrics
#
# This configuration allows KEDA to query OpenShift Monitoring (Thanos) metrics.
# The KEDA operator uses the ServiceAccount token for bearer authentication.
#
# Ref: https://keda.sh/docs/2.16/scalers/prometheus/
# Ref: https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/nodes/index#nodes-cma-autoscaling-custom

---
# ServiceAccount for KEDA metric queries
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-prometheus-sa
  namespace: private-ai
  labels:
    app.kubernetes.io/name: keda-auth
    app.kubernetes.io/component: autoscaling
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
# Secret with ServiceAccount token (auto-populated by OpenShift)
apiVersion: v1
kind: Secret
metadata:
  name: keda-prometheus-token
  namespace: private-ai
  labels:
    app.kubernetes.io/name: keda-auth
    app.kubernetes.io/component: autoscaling
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    kubernetes.io/service-account.name: keda-prometheus-sa
type: kubernetes.io/service-account-token
---
# RoleBinding to allow KEDA SA to query Thanos (tenancy mode - port 9092)
# Port 9092 requires 'view' role in the specific project
# Ref: oc get svc thanos-querier -n openshift-monitoring -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keda-prometheus-view
  namespace: private-ai
  labels:
    app.kubernetes.io/name: keda-auth
    app.kubernetes.io/component: autoscaling
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view  # Built-in OCP role for Thanos tenancy mode (port 9092)
subjects:
  - kind: ServiceAccount
    name: keda-prometheus-sa
    namespace: private-ai
---
# TriggerAuthentication for Prometheus/Thanos access
# Ref: https://developers.redhat.com/articles/2025/09/23/how-set-kserve-autoscaling-vllm-keda
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-prometheus
  namespace: private-ai
  labels:
    app.kubernetes.io/name: keda-auth
    app.kubernetes.io/component: autoscaling
    demo.rhoai.io/step: "08"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    openshift.io/description: "Authentication for KEDA to access Thanos metrics"
spec:
  secretTargetRef:
    - parameter: bearerToken
      name: keda-prometheus-token
      key: token
    - parameter: ca
      name: keda-prometheus-token
      key: ca.crt

